"use client";
import { useEffect, useState } from "react";
import { copy, languageNames, Locale, locales, PageKey, residenceData, routeFor, detailCopy } from "../site-data";

const IMG={hero:"https://static.tildacdn.one/tild3564-6632-4233-b537-643562376632/03_Riverside_horizon.jpg",bedroom:"https://static.tildacdn.one/tild3265-3036-4731-a536-303865323665/15_Bedroom_closeup_s.jpg",ocean:"https://static.tildacdn.one/tild3266-6134-4136-a537-623239333736/10_Ocean_View.jpg",beach:"https://static.tildacdn.one/tild3837-6232-4330-a337-326663353334/05_Beach_horizontal.jpg",terrace:"https://static.tildacdn.one/tild3637-3037-4536-b835-343835653738/09_Terrace_horizonta.jpg",nuanu:"https://optim.tildacdn.one/tild6533-6538-4735-b964-656535613034/-/resize/800x1000/-/format/webp/2026-06-17_121936.jpg.webp",art:"https://optim.tildacdn.one/tild6631-3736-4430-b936-353166313438/-/resize/600x600/-/format/webp/2026-06-17_121939.jpg.webp"};
const split=(s:string)=>s.split("|");

function LocaleDocument({locale}:{locale:Locale}){useEffect(()=>{document.documentElement.lang=locale},[locale]);return null}

function Header({locale,dark=false}:{locale:Locale;dark?:boolean}){
 const [menu,setMenu]=useState(false); const t=copy[locale];
 return <header className={`nav ${dark?"nav-dark":""} ${menu?"menu-active":""}`}><a className="brand wordmark" href={routeFor(locale)} aria-label="Luna Residences"><span>LUNA<br/><small>RESIDENCES</small></span></a><nav className={menu?"nav-links open":"nav-links"}><div className="mobile-menu-label">MENU · LUNA RESIDENCES</div><a href={routeFor(locale)} onClick={()=>setMenu(false)}><span>01</span>{t.nav[0]}</a><a href={routeFor(locale,"residences")} onClick={()=>setMenu(false)}><span>02</span>{t.nav[1]}</a><a href={routeFor(locale,"investment")} onClick={()=>setMenu(false)}><span>03</span>{t.nav[2]}</a><a href={routeFor(locale,"nuanu")} onClick={()=>setMenu(false)}><span>04</span>{t.nav[3]}</a><a href={routeFor(locale,"buying-guide")} onClick={()=>setMenu(false)}><span>05</span>Guide</a><div className="mobile-languages"><small>LANGUAGE</small>{locales.map(l=><a className={l===locale?"active":""} key={l} href={routeFor(l)} lang={l} hrefLang={l}>{languageNames[l]}</a>)}</div></nav><div className="nav-actions"><div className="language"><button aria-label="Choose language"><span>{languageNames[locale]}</span><i>⌄</i></button><div>{locales.map(l=><a className={l===locale?"active":""} key={l} href={routeFor(l)} lang={l} hrefLang={l}><span>{languageNames[l]}</span>{l===locale&&<b>●</b>}</a>)}</div></div><a className="nav-cta" href="#contact">{t.brochure} <span>↗</span></a></div><button className="menu" onClick={()=>setMenu(!menu)} aria-label={menu?"Close menu":"Open menu"} aria-expanded={menu}><span>{menu?"CLOSE":"MENU"}</span><i>{menu?"×":"+"}</i></button></header>
}

function LeadForm({locale}:{locale:Locale}){const t=copy[locale];return <section className="contact" id="contact"><div className="contact-copy"><p className="eyebrow light"><span/>{t.contact}</p><h2>{split(t.contactTitle)[0]}<br/><em>{split(t.contactTitle)[1]}</em></h2><p>{t.contactBody}</p><div className="contact-note"><span>✓</span><p>{t.response}<br/><small>{t.privacy}</small></p></div></div><div className="tally-wrap"><iframe data-tally-src="https://tally.so/embed/44DXKd?alignLeft=1&hideTitle=1&transparentBackground=1&dynamicHeight=1" loading="lazy" width="100%" height="448" frameBorder="0" marginHeight={0} marginWidth={0} title="GTP-Luna Residences"/></div></section>}

const footerSeo:Record<Locale,{about:string;quick:string;explore:string;topics:string;links:string[];topicLinks:string[]}>={
 en:{about:"Luna Residences is a limited collection of ocean-view residences for sale in Nuanu Creative City, Bali. Designed by YODEZEEN and located near Nyanyi Beach, the project combines tropical living, long-term leasehold ownership and five-star property management.",quick:"Quick links",explore:"Explore Luna",topics:"Popular searches",links:["Ocean-view residences in Bali","Luxury property in Nuanu","Bali property investment","Residences near Nyanyi Beach"],topicLinks:["Luna Beach Club residences","YODEZEEN interiors Bali","60+ year Bali leasehold","Nuanu Creative City real estate"]},
 fr:{about:"Luna Residences est une collection limitée de résidences avec vue océan à vendre au cœur de Nuanu Creative City, à Bali. Signé YODEZEEN et situé près de Nyanyi Beach, le projet associe art de vivre tropical, leasehold longue durée et gestion immobilière 5 étoiles.",quick:"Liens rapides",explore:"Découvrir Luna",topics:"Recherches populaires",links:["Résidences avec vue mer à Bali","Immobilier de luxe à Nuanu","Investissement immobilier à Bali","Résidences près de Nyanyi Beach"],topicLinks:["Résidences Luna Beach Club","Intérieurs YODEZEEN à Bali","Leasehold 60+ ans à Bali","Immobilier Nuanu Creative City"]},
 es:{about:"Luna Residences es una colección limitada de residencias con vistas al océano en venta en Nuanu Creative City, Bali. Diseñado por YODEZEEN y cerca de Nyanyi Beach, combina vida tropical, leasehold de larga duración y gestión inmobiliaria de cinco estrellas.",quick:"Enlaces rápidos",explore:"Descubrir Luna",topics:"Búsquedas populares",links:["Residencias con vista al mar en Bali","Propiedad de lujo en Nuanu","Inversión inmobiliaria en Bali","Residencias cerca de Nyanyi Beach"],topicLinks:["Residencias Luna Beach Club","Interiores YODEZEEN en Bali","Leasehold 60+ años en Bali","Inmuebles en Nuanu Creative City"]},
 pt:{about:"Luna Residences é uma coleção limitada de residências com vista para o oceano à venda em Nuanu Creative City, Bali. Projetado pela YODEZEEN e perto de Nyanyi Beach, combina estilo de vida tropical, leasehold de longo prazo e gestão imobiliária cinco estrelas.",quick:"Links rápidos",explore:"Conheça Luna",topics:"Pesquisas populares",links:["Residências com vista para o mar em Bali","Imóveis de luxo em Nuanu","Investimento imobiliário em Bali","Residências perto de Nyanyi Beach"],topicLinks:["Residências Luna Beach Club","Interiores YODEZEEN em Bali","Leasehold 60+ anos em Bali","Imóveis em Nuanu Creative City"]}
};

function Footer({locale}:{locale:Locale}){const s=footerSeo[locale],t=copy[locale];return <footer className="seo-footer"><div className="footer-intro"><a className="brand footer-brand wordmark" href={routeFor(locale)}><span>LUNA<br/><small>RESIDENCES</small></span></a><p>{s.about}</p><span>NUANU CREATIVE CITY · BERABAN · TABANAN · BALI</span></div><nav aria-label={s.quick}><h3>{s.quick}</h3><a href={routeFor(locale)}>{t.nav[0]}</a><a href={routeFor(locale,"residences")}>{t.pageTitles.residences}</a><a href={routeFor(locale,"investment")}>{t.pageTitles.investment}</a><a href={routeFor(locale,"nuanu")}>{t.pageTitles.nuanu}</a><a href={routeFor(locale,"buying-guide")}>{t.pageTitles["buying-guide"]}</a></nav><nav aria-label={s.explore}><h3>{s.explore}</h3>{s.links.map((label,i)=><a key={label} href={routeFor(locale,(["residences","residences","investment","nuanu"] as PageKey[])[i])}>{label}</a>)}</nav><nav aria-label={s.topics}><h3>{s.topics}</h3>{s.topicLinks.map((label,i)=><a key={label} href={routeFor(locale,(["nuanu","residences","buying-guide","investment"] as PageKey[])[i])}>{label}</a>)}</nav><div className="footer-languages"><span>LANGUAGE</span>{locales.map(l=><a className={l===locale?"active":""} key={l} href={routeFor(l)} hrefLang={l}>{languageNames[l]}</a>)}</div><small className="footer-bottom"><span>© 2026 LUNA RESIDENCES · {t.footer}</span><a href="https://ioagency.ae" target="_blank" rel="noopener noreferrer">Designed by <strong>BONJOURS</strong></a></small></footer>}

export function HomePage({locale}:{locale:Locale}){const t=copy[locale];const rs=residenceData[locale];const faq=[t.disclaimer,t.visionBody,t.investBody];return <main><LocaleDocument locale={locale}/><Header locale={locale}/><section className="hero" style={{backgroundImage:`url(${IMG.hero})`}}><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow light"><span/>NUANU CREATIVE CITY · BALI</p><h1>{split(t.hero)[0]}<br/><em>{split(t.hero)[1]}</em></h1><p className="hero-intro">{t.intro}</p><div className="hero-actions"><a className="btn primary" href="#contact">{t.access}<span>↗</span></a><a className="text-link" href="#vision">{t.discover}<span>↓</span></a></div></div><div className="hero-stats"><div><strong>{t.from}</strong><b>185,000 USD</b></div><div><strong>{t.collection}</strong><b>15 residences</b></div><div><strong>{t.delivery}</strong><b>Q4 2028</b></div></div></section>
 <section className="manifesto" id="vision"><div><p className="eyebrow"><span/>{t.vision}</p><h2>{split(t.visionTitle).map((x:string,i:number)=><span key={x}>{x}{i<2&&<br/>}</span>)}</h2></div><div className="manifesto-copy"><p className="lead">{t.visionLead}</p><p>{t.visionBody}</p><div className="signature">YODEZEEN <small>ARCHITECTURE & INTERIORS</small></div></div></section>
 <section className="image-break" style={{backgroundImage:`url(${IMG.terrace})`}}/>
 <section className="numbers"><p className="eyebrow light"><span/>{t.essentials}</p><div className="number-grid"><article><b>10–14<sup>%</sup></b><p>{t.roi}</p></article><article><b>60<sup>+ years</sup></b><p>{t.lease}</p></article><article><b>25<sup>%</sup></b><p>{t.down}</p></article><article><b>300<sup>m</sup></b><p>{t.beach}</p></article></div><small>{t.disclaimer}</small></section>
 <section className="residences"><div className="section-head"><div><p className="eyebrow"><span/>{t.coll}</p><h2>{split(t.collTitle)[0]}<br/><em>{split(t.collTitle)[1]}</em></h2></div><p>{t.collIntro}</p></div><div className="residence-layout"><div className="residence-list">{rs.map((r:any,i:number)=><article key={r.title}><span>0{i+1}</span><div><h3>{r.title}</h3><p>{r.desc}</p><div className="tags"><b>{r.area}</b><b>{r.terrace}</b></div></div><a href={routeFor(locale,"residences")}>↗</a></article>)}</div><div className="sticky-image" style={{backgroundImage:`url(${IMG.bedroom})`}}/></div></section>
 <section className="lifestyle"><div className="lifestyle-grid"><img src={IMG.beach} alt="Nyanyi Beach near Luna Residences"/><div><p className="eyebrow light"><span/>{t.lifestyle}</p><h2>{split(t.lifestyleTitle)[0]}<br/><em>{split(t.lifestyleTitle)[1]}</em></h2><p>{t.lifestyleBody}</p></div><img src={IMG.ocean} alt="Ocean view from Luna Residences"/></div><div className="perks">{[["Luna Black Card","VIP access & priority reservations"],["In-residence dining","Luna hospitality, served at home"],["Daily shuttle","Easy movement throughout Nuanu"],["Resident events","Curated cultural programming"]].map((p,i)=><article key={p[0]}><span>0{i+1}</span><h3>{p[0]}</h3><p>{p[1]}</p></article>)}</div></section>
 <section className="nuanu"><div className="nuanu-copy"><p className="eyebrow"><span/>NUANU CREATIVE CITY</p><h2>{split(t.nuanuTitle)[0]}<br/>{split(t.nuanuTitle)[1]}</h2><p>{t.nuanuBody}</p><a className="text-link dark" href={routeFor(locale,"nuanu")}>{t.discover}<span>↗</span></a></div><div className="nuanu-collage"><img className="nuanu-tall" src={IMG.nuanu} alt="Nuanu Creative City Bali"/><img className="nuanu-small" src={IMG.art} alt="Art and nature in Nuanu"/><div className="nuanu-badge"><b>1M+</b><span>annual visitors</span></div></div><div className="ecosystem"><div><b>12 ha</b><span>parks</span></div><div><b>365</b><span>days alive</span></div><div><b>30+</b><span>destinations</span></div><div><b>70%</b><span>nature</span></div></div></section>
 <section className="investment"><div className="invest-image" style={{backgroundImage:`url(${IMG.ocean})`}}/><div className="invest-copy"><p className="eyebrow light"><span/>{t.invest}</p><h2>{split(t.investTitle)[0]}<br/><em>{split(t.investTitle)[1]}</em></h2><p>{t.investBody}</p><ul><li><span>01</span>5-star 24/7 management</li><li><span>02</span>Fully managed rentals</li><li><span>03</span>Q4 2028 handover</li><li><span>04</span>Ocean, river & jungle views</li></ul><a className="btn sand" href={routeFor(locale,"investment")}>{t.discover}<span>↗</span></a></div></section>
 <section className="payment"><div><p className="eyebrow"><span/>{t.payment}</p><h2>{split(t.paymentTitle)[0]}<br/><em>{split(t.paymentTitle)[1]}</em></h2></div><div className="timeline">{[["25%","Signing"],["25%","Q1 2027"],["25%","Q1 2028"],["25%","Handover"]].map((x,i)=><article key={x[1]}><span>0{i+1}</span><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></section>
 <section className="faq"><div><p className="eyebrow"><span/>{t.faq}</p><h2>{split(t.faqTitle)[0]}<br/><em>{split(t.faqTitle)[1]}</em></h2></div><div className="faq-list">{faq.map((x:string,i:number)=><article className="active" key={x}><button><span>0{i+1}</span>{[t.roi,t.lease,t.invest][i]}<b>−</b></button><p>{x}</p></article>)}</div></section><LeadForm locale={locale}/><Footer locale={locale}/><a className="mobile-tally-cta" href="#contact">{t.brochure}<span>↗</span></a></main>}

export function DetailPage({locale,page}:{locale:Locale;page:PageKey}){const t=copy[locale],d=detailCopy[locale][page];return <main><LocaleDocument locale={locale}/><Header locale={locale}/><section className="inner-hero" style={{backgroundImage:`url(${page==="nuanu"?IMG.nuanu:page==="residences"?IMG.bedroom:IMG.hero})`}}><div className="hero-shade"/><div><p className="eyebrow light"><span/>{t.pageKickers[page]}</p><h1>{t.pageTitles[page]}</h1><p>{d.intro}</p></div></section><section className="detail-sections">{d.sections.map((s:any,i:number)=><article key={s.title}><span>0{i+1}</span><h2>{s.title}</h2><p>{s.body}</p></article>)}</section><section className="detail-cta"><p className="eyebrow"><span/>LUNA RESIDENCES</p><h2>{t.contactTitle.replace("|"," ")}</h2><a className="btn sand" href="#contact">{t.brochure}<span>↗</span></a></section><LeadForm locale={locale}/><Footer locale={locale}/><a className="mobile-tally-cta" href="#contact">{t.brochure}<span>↗</span></a></main>}

export function EditorialPage({locale,title,kicker,intro,sections,related}:{locale:Locale;title:string;kicker:string;intro:string;sections:{title:string;body:string}[];related:string}){const t=copy[locale];return <main><LocaleDocument locale={locale}/><Header locale={locale}/><section className="inner-hero editorial-hero"><div className="hero-shade"/><div><p className="eyebrow light"><span/>{kicker}</p><h1>{title}</h1><p>{intro}</p></div></section><article className="detail-sections editorial-sections">{sections.map((s,i)=><section key={s.title}><span>0{i+1}</span><h2>{s.title}</h2><p>{s.body}</p></section>)}</article><nav className="editorial-related" aria-label={related}><strong>{related}</strong><a href={routeFor(locale,"residences")}>{t.pageTitles.residences}</a><a href={routeFor(locale,"investment")}>{t.pageTitles.investment}</a><a href={routeFor(locale,"buying-guide")}>{t.pageTitles["buying-guide"]}</a><a href={routeFor(locale,"nuanu")}>{t.pageTitles.nuanu}</a></nav><section className="detail-cta"><p className="eyebrow"><span/>LUNA RESIDENCES</p><h2>{t.contactTitle.replace("|"," ")}</h2><a className="btn sand" href="#contact">{t.brochure}<span>↗</span></a></section><LeadForm locale={locale}/><Footer locale={locale}/><a className="mobile-tally-cta" href="#contact">{t.brochure}<span>↗</span></a></main>}
