"use client";
import { FormEvent, useState } from "react";
import { copy, languageNames, Locale, locales, PageKey, residenceData, routeFor, detailCopy } from "../site-data";

const IMG={hero:"https://static.tildacdn.one/tild3564-6632-4233-b537-643562376632/03_Riverside_horizon.jpg",bedroom:"https://static.tildacdn.one/tild3265-3036-4731-a536-303865323665/15_Bedroom_closeup_s.jpg",ocean:"https://static.tildacdn.one/tild3266-6134-4136-a537-623239333736/10_Ocean_View.jpg",beach:"https://static.tildacdn.one/tild3837-6232-4330-a337-326663353334/05_Beach_horizontal.jpg",terrace:"https://static.tildacdn.one/tild3637-3037-4536-b835-343835653738/09_Terrace_horizonta.jpg",nuanu:"https://optim.tildacdn.one/tild6533-6538-4735-b964-656535613034/-/resize/800x1000/-/format/webp/2026-06-17_121936.jpg.webp",art:"https://optim.tildacdn.one/tild6631-3736-4430-b936-353166313438/-/resize/600x600/-/format/webp/2026-06-17_121939.jpg.webp"};
const whatsapp="6282340644814";
const split=(s:string)=>s.split("|");

function Header({locale,dark=false}:{locale:Locale;dark?:boolean}){
 const [menu,setMenu]=useState(false); const t=copy[locale];
 return <header className={`nav ${dark?"nav-dark":""}`}><a className="brand" href={routeFor(locale)} aria-label="Luna Residences"><span className="brand-mark">L</span><span>LUNA<br/><small>RESIDENCES</small></span></a><nav className={menu?"nav-links open":"nav-links"}><a href={routeFor(locale)}>{t.nav[0]}</a><a href={routeFor(locale,"residences")}>{t.nav[1]}</a><a href={routeFor(locale,"investment")}>{t.nav[2]}</a><a href={routeFor(locale,"nuanu")}>{t.nav[3]}</a><a href={routeFor(locale,"buying-guide")}>Guide</a></nav><div className="nav-actions"><div className="language"><button aria-label="Choose language">{languageNames[locale]}⌄</button><div>{locales.map(l=><a key={l} href={routeFor(l)} lang={l} hrefLang={l}>{languageNames[l]}</a>)}</div></div><a className="nav-cta" href="#contact">{t.brochure} <span>↗</span></a></div><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Menu">{menu?"×":"☰"}</button></header>
}

function LeadForm({locale}:{locale:Locale}){const t=copy[locale];function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const msg=`Luna Residences lead (${locale.toUpperCase()})\nName: ${d.get("name")}\nPhone: ${d.get("phone")}\nBudget: ${d.get("budget")}\nGoal: ${d.get("goal")}`;window.open(`https://wa.me/${whatsapp}?text=${encodeURIComponent(msg)}`,"_blank","noopener,noreferrer")}
 return <section className="contact" id="contact"><div className="contact-copy"><p className="eyebrow light"><span/>{t.contact}</p><h2>{split(t.contactTitle)[0]}<br/><em>{split(t.contactTitle)[1]}</em></h2><p>{t.contactBody}</p><div className="contact-note"><span>✓</span><p>{t.response}<br/><small>{t.privacy}</small></p></div></div><form onSubmit={submit}><label>{t.name}<input required name="name" autoComplete="name"/></label><label>{t.phone}<input required name="phone" type="tel" autoComplete="tel"/></label><div className="form-row"><label>{t.budget}<select name="budget" defaultValue=""><option value="" disabled>{t.select}</option><option>185k–300k USD</option><option>300k–500k USD</option><option>500k+ USD</option></select></label><label>{t.goal}<select name="goal" defaultValue=""><option value="" disabled>{t.select}</option><option>Investment</option><option>Residence</option><option>Hybrid use</option></select></label></div><label className="consent"><input type="checkbox" required/> {t.consent}</label><button className="btn primary submit">{t.submit}<span>↗</span></button></form></section>}

function Footer({locale}:{locale:Locale}){return <footer><a className="brand footer-brand" href={routeFor(locale)}><span className="brand-mark">L</span><span>LUNA<br/><small>RESIDENCES</small></span></a><div><p>NUANU CREATIVE CITY<br/>BERABAN · TABANAN · BALI</p></div><div><a href="mailto:igor@nuanu.realestate">igor@nuanu.realestate</a><a href="tel:+6282340644814">+62 823 4064 4814</a></div><div><a href={routeFor(locale,"residences")}>{copy[locale].nav[1]}</a><a href={routeFor(locale,"investment")}>{copy[locale].nav[2]}</a><a href={routeFor(locale,"buying-guide")}>Guide</a></div><small>© 2026 LUNA RESIDENCES · {copy[locale].footer}</small></footer>}

export function HomePage({locale}:{locale:Locale}){const t=copy[locale];const rs=residenceData[locale];const faq=[t.disclaimer,t.visionBody,t.investBody];return <main><Header locale={locale}/><section className="hero" style={{backgroundImage:`url(${IMG.hero})`}}><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow light"><span/>NUANU CREATIVE CITY · BALI</p><h1>{split(t.hero)[0]}<br/><em>{split(t.hero)[1]}</em></h1><p className="hero-intro">{t.intro}</p><div className="hero-actions"><a className="btn primary" href="#contact">{t.access}<span>↗</span></a><a className="text-link" href="#vision">{t.discover}<span>↓</span></a></div></div><div className="hero-stats"><div><strong>{t.from}</strong><b>185,000 USD</b></div><div><strong>{t.collection}</strong><b>15 residences</b></div><div><strong>{t.delivery}</strong><b>Q4 2028</b></div></div></section>
 <section className="manifesto" id="vision"><div><p className="eyebrow"><span/>{t.vision}</p><h2>{split(t.visionTitle).map((x:string,i:number)=><span key={x}>{x}{i<2&&<br/>}</span>)}</h2></div><div className="manifesto-copy"><p className="lead">{t.visionLead}</p><p>{t.visionBody}</p><div className="signature">YODEZEEN <small>ARCHITECTURE & INTERIORS</small></div></div></section>
 <section className="image-break" style={{backgroundImage:`url(${IMG.terrace})`}}/>
 <section className="numbers"><p className="eyebrow light"><span/>{t.essentials}</p><div className="number-grid"><article><b>10–14<sup>%</sup></b><p>{t.roi}</p></article><article><b>60<sup>+ years</sup></b><p>{t.lease}</p></article><article><b>25<sup>%</sup></b><p>{t.down}</p></article><article><b>300<sup>m</sup></b><p>{t.beach}</p></article></div><small>{t.disclaimer}</small></section>
 <section className="residences"><div className="section-head"><div><p className="eyebrow"><span/>{t.coll}</p><h2>{split(t.collTitle)[0]}<br/><em>{split(t.collTitle)[1]}</em></h2></div><p>{t.collIntro}</p></div><div className="residence-layout"><div className="residence-list">{rs.map((r:any,i:number)=><article key={r.title}><span>0{i+1}</span><div><h3>{r.title}</h3><p>{r.desc}</p><div className="tags"><b>{r.area}</b><b>{r.terrace}</b></div></div><a href={routeFor(locale,"residences")}>↗</a></article>)}</div><div className="sticky-image" style={{backgroundImage:`url(${IMG.bedroom})`}}/></div></section>
 <section className="lifestyle"><div className="lifestyle-grid"><img src={IMG.beach} alt="Nyanyi Beach near Luna Residences"/><div><p className="eyebrow light"><span/>{t.lifestyle}</p><h2>{split(t.lifestyleTitle)[0]}<br/><em>{split(t.lifestyleTitle)[1]}</em></h2><p>{t.lifestyleBody}</p></div><img src={IMG.ocean} alt="Ocean view from Luna Residences"/></div><div className="perks">{[["Luna Black Card","VIP access & priority reservations"],["In-residence dining","Luna hospitality, served at home"],["Daily shuttle","Easy movement throughout Nuanu"],["Resident events","Curated cultural programming"]].map((p,i)=><article key={p[0]}><span>0{i+1}</span><h3>{p[0]}</h3><p>{p[1]}</p></article>)}</div></section>
 <section className="nuanu"><div className="nuanu-copy"><p className="eyebrow"><span/>NUANU CREATIVE CITY</p><h2>{split(t.nuanuTitle)[0]}<br/>{split(t.nuanuTitle)[1]}</h2><p>{t.nuanuBody}</p><a className="text-link dark" href={routeFor(locale,"nuanu")}>{t.discover}<span>↗</span></a></div><div className="nuanu-collage"><img className="nuanu-tall" src={IMG.nuanu} alt="Nuanu Creative City Bali"/><img className="nuanu-small" src={IMG.art} alt="Art and nature in Nuanu"/><div className="nuanu-badge"><b>1M+</b><span>annual visitors</span></div></div><div className="ecosystem"><div><b>12 ha</b><span>parks</span></div><div><b>365</b><span>days alive</span></div><div><b>30+</b><span>destinations</span></div><div><b>70%</b><span>nature</span></div></div></section>
 <section className="investment"><div className="invest-image" style={{backgroundImage:`url(${IMG.ocean})`}}/><div className="invest-copy"><p className="eyebrow light"><span/>{t.invest}</p><h2>{split(t.investTitle)[0]}<br/><em>{split(t.investTitle)[1]}</em></h2><p>{t.investBody}</p><ul><li><span>01</span>5-star 24/7 management</li><li><span>02</span>Fully managed rentals</li><li><span>03</span>Q4 2028 handover</li><li><span>04</span>Ocean, river & jungle views</li></ul><a className="btn sand" href={routeFor(locale,"investment")}>{t.discover}<span>↗</span></a></div></section>
 <section className="payment"><div><p className="eyebrow"><span/>{t.payment}</p><h2>{split(t.paymentTitle)[0]}<br/><em>{split(t.paymentTitle)[1]}</em></h2></div><div className="timeline">{[["25%","Signing"],["25%","Q1 2027"],["25%","Q1 2028"],["25%","Handover"]].map((x,i)=><article key={x[1]}><span>0{i+1}</span><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></section>
 <section className="faq"><div><p className="eyebrow"><span/>{t.faq}</p><h2>{split(t.faqTitle)[0]}<br/><em>{split(t.faqTitle)[1]}</em></h2></div><div className="faq-list">{faq.map((x:string,i:number)=><article className="active" key={x}><button><span>0{i+1}</span>{[t.roi,t.lease,t.invest][i]}<b>−</b></button><p>{x}</p></article>)}</div></section><LeadForm locale={locale}/><Footer locale={locale}/><a className="floating-wa" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer" aria-label="WhatsApp">WA</a></main>}

export function DetailPage({locale,page}:{locale:Locale;page:PageKey}){const t=copy[locale],d=detailCopy[locale][page];return <main><Header locale={locale}/><section className="inner-hero" style={{backgroundImage:`url(${page==="nuanu"?IMG.nuanu:page==="residences"?IMG.bedroom:IMG.hero})`}}><div className="hero-shade"/><div><p className="eyebrow light"><span/>{t.pageKickers[page]}</p><h1>{t.pageTitles[page]}</h1><p>{d.intro}</p></div></section><section className="detail-sections">{d.sections.map((s:any,i:number)=><article key={s.title}><span>0{i+1}</span><h2>{s.title}</h2><p>{s.body}</p></article>)}</section><section className="detail-cta"><p className="eyebrow"><span/>LUNA RESIDENCES</p><h2>{t.contactTitle.replace("|"," ")}</h2><a className="btn sand" href="#contact">{t.brochure}<span>↗</span></a></section><LeadForm locale={locale}/><Footer locale={locale}/></main>}
