import type {Locale} from "./site-data";
export const architectureSlug="tropical-architecture-bali-luna-residences";
const images=["/luna-residences-river-sunset-bali.webp","/luna-residences-tropical-facade-bali.webp","/luna-residences-entrance-courtyard-bali.webp","/luna-residences-rain-responsive-architecture.webp","/luna-residences-layered-terraces-bali.webp","/luna-residences-river-terraces-nuanu.webp","/luna-residences-aerial-river-nuanu.webp"];
const data={
en:{title:"Tropical architecture in Bali: inside Luna Residences",kicker:"ARCHITECTURE & DESIGN",intro:"Luna Residences translates Bali’s river, jungle and coastal climate into layered architecture by YODEZEEN. Explore how terraces, shade, planting and flowing forms shape the project.",related:"Explore the Luna collection",sections:[
 {title:"Architecture shaped by the landscape",body:"Rather than treating the site as a backdrop, the design follows its river edge, tropical vegetation and long views. Horizontal layers make the building appear to extend from the landscape, while curved edges soften its scale. From a distance, the composition reads as a series of planted terraces; closer views reveal sheltered outdoor rooms and transitions between architecture and nature."},
 {title:"Deep terraces create shade and privacy",body:"Bali’s sun and seasonal rain make covered outdoor space essential. The projecting terrace lines shown in the renderings provide shade to glazed interiors and help separate neighbouring residences visually. Planting along the edges creates another layer between private rooms and the wider landscape. These elements are not simply decorative: they influence comfort, views and the way each residence connects to the outdoors."},
 {title:"A fluid arrival experience",body:"The entrance sequence uses curved openings, filtered daylight, mist and tropical planting to create a gradual transition from destination to residence. Instead of a conventional enclosed lobby, the architectural language continues through the shared spaces. The central opening draws light deep into the arrival court and gives the building an identifiable heart, while natural textures reinforce the connection with Nuanu’s landscape."},
 {title:"Designed for changing tropical weather",body:"Architecture in Bali must respond to intense light, humidity and heavy rain. The rain view illustrates how broad overhangs and protected circulation can support movement around the building in different conditions. Durable detailing, drainage and ongoing maintenance remain as important as the visual concept. Prospective owners should confirm final material specifications and operational responsibilities in the project documentation."},
 {title:"Views become part of the floor plan",body:"Ocean, river and jungle outlooks are framed by terraces rather than added as a final feature. The aerial and sunset views show how the building bends around the water and how each level gains a different relationship with the horizon. When choosing a residence, compare the exact orientation, terrace depth and foreground for each available unit alongside the interior plan."}
],captions:["Luna Residences at sunset beside the river","Layered tropical façade and planted terraces","Arrival courtyard with filtered natural light","Sheltered circulation during tropical rain","Private terraces facing the jungle landscape","River-facing planted terraces","Aerial view of Luna Residences within Nuanu"]},
fr:{title:"Architecture tropicale à Bali : Luna Residences",kicker:"ARCHITECTURE & DESIGN",intro:"Luna Residences traduit la rivière, la jungle et le climat côtier de Bali en une architecture stratifiée signée YODEZEEN. Découvrez le rôle des terrasses, de l’ombre, de la végétation et des lignes fluides.",related:"Découvrir la collection Luna",sections:[
 {title:"Une architecture façonnée par le paysage",body:"Le projet ne traite pas le site comme un simple décor : il suit la rivière, la végétation tropicale et les vues lointaines. Les lignes horizontales prolongent visuellement le paysage tandis que les courbes adoucissent l’échelle du bâtiment. De loin, la composition ressemble à une succession de terrasses plantées ; de près, elle révèle des espaces extérieurs abrités et des transitions entre architecture et nature."},
 {title:"Des terrasses profondes pour l’ombre et l’intimité",body:"Le soleil et les pluies saisonnières de Bali rendent les espaces extérieurs couverts essentiels. Les terrasses en saillie protègent les baies vitrées et séparent visuellement les résidences voisines. La végétation en périphérie crée un filtre supplémentaire entre les pièces privées et le paysage. Ces éléments influencent directement le confort, les vues et la relation quotidienne avec l’extérieur."},
 {title:"Une arrivée fluide et immersive",body:"L’entrée associe ouvertures courbes, lumière filtrée, brume et végétation tropicale pour créer une transition progressive vers les résidences. Plutôt qu’un hall fermé conventionnel, le langage architectural se poursuit dans les espaces communs. L’ouverture centrale apporte la lumière au cœur de l’arrivée et donne une identité forte au bâtiment, tandis que les textures naturelles prolongent le paysage de Nuanu."},
 {title:"Conçue pour le climat tropical",body:"À Bali, l’architecture doit répondre à la lumière intense, à l’humidité et aux pluies fortes. La vue sous la pluie illustre le rôle des grands débords et des circulations protégées. Le drainage, les détails constructifs durables et l’entretien sont aussi importants que le concept visuel. Les futurs propriétaires doivent vérifier les matériaux définitifs et les responsabilités de gestion dans la documentation du projet."},
 {title:"Les vues intégrées aux plans",body:"Les perspectives sur l’océan, la rivière et la jungle sont cadrées par les terrasses dès la conception. Les vues aériennes et au coucher du soleil montrent comment le bâtiment épouse l’eau et comment chaque niveau entretient une relation différente avec l’horizon. Pour choisir une résidence, comparez précisément orientation, profondeur de terrasse, premier plan et distribution intérieure."}
],captions:["Luna Residences au coucher du soleil près de la rivière","Façade tropicale stratifiée et terrasses plantées","Cour d’arrivée éclairée naturellement","Circulations protégées pendant la pluie tropicale","Terrasses privées face au paysage de jungle","Terrasses végétalisées donnant sur la rivière","Vue aérienne de Luna Residences dans Nuanu"]},
es:{title:"Arquitectura tropical en Bali: Luna Residences",kicker:"ARQUITECTURA Y DISEÑO",intro:"Luna Residences convierte el río, la selva y el clima costero de Bali en una arquitectura estratificada de YODEZEEN. Descubre cómo terrazas, sombra, vegetación y formas fluidas definen el proyecto.",related:"Descubre la colección Luna",sections:[
 {title:"Arquitectura moldeada por el paisaje",body:"El diseño no trata el lugar como un simple fondo: sigue el río, la vegetación tropical y las vistas largas. Las capas horizontales prolongan visualmente el paisaje y los bordes curvos suavizan la escala. Desde lejos, el edificio parece una serie de terrazas plantadas; de cerca, revela espacios exteriores protegidos y transiciones continuas entre arquitectura y naturaleza."},
 {title:"Terrazas profundas, sombra y privacidad",body:"El sol y la lluvia estacional de Bali hacen esencial el espacio exterior cubierto. Las terrazas salientes dan sombra a los interiores acristalados y separan visualmente las viviendas. La vegetación crea otro filtro entre las habitaciones privadas y el paisaje. No son elementos puramente decorativos: determinan el confort, las vistas y la conexión cotidiana con el exterior."},
 {title:"Una llegada fluida",body:"La entrada combina aberturas curvas, luz filtrada, niebla y plantas tropicales para crear una transición gradual. En lugar de un vestíbulo cerrado convencional, el lenguaje arquitectónico continúa por las zonas comunes. La abertura central lleva luz al corazón del patio y da identidad al edificio, mientras las texturas naturales refuerzan la relación con el paisaje de Nuanu."},
 {title:"Diseñada para el clima tropical",body:"La arquitectura de Bali debe responder a luz intensa, humedad y lluvias fuertes. La imagen bajo la lluvia muestra cómo los grandes voladizos y recorridos protegidos permiten usar el edificio en distintas condiciones. Drenaje, detalles duraderos y mantenimiento son tan importantes como el concepto visual. Conviene confirmar materiales finales y responsabilidades operativas en la documentación."},
 {title:"Las vistas forman parte de la planta",body:"Las perspectivas al océano, río y selva se enmarcan mediante las terrazas desde el inicio. Las vistas aérea y del atardecer muestran cómo el edificio sigue el agua y cómo cada nivel se relaciona de manera distinta con el horizonte. Al elegir una unidad, compara orientación exacta, profundidad de terraza, primer plano y distribución interior."}
],captions:["Luna Residences al atardecer junto al río","Fachada tropical estratificada y terrazas verdes","Patio de entrada con luz natural filtrada","Circulación protegida durante la lluvia tropical","Terrazas privadas frente a la selva","Terrazas plantadas orientadas al río","Vista aérea de Luna Residences en Nuanu"]},
pt:{title:"Arquitetura tropical em Bali: Luna Residences",kicker:"ARQUITETURA E DESIGN",intro:"Luna Residences transforma o rio, a floresta e o clima costeiro de Bali em uma arquitetura em camadas da YODEZEEN. Veja como terraços, sombra, vegetação e formas fluidas definem o projeto.",related:"Conheça a coleção Luna",sections:[
 {title:"Arquitetura moldada pela paisagem",body:"O projeto não trata o local como simples cenário: acompanha o rio, a vegetação tropical e as vistas longas. As camadas horizontais prolongam visualmente a paisagem e as bordas curvas suavizam a escala. De longe, o edifício parece uma sequência de terraços plantados; de perto, revela áreas externas protegidas e transições contínuas entre arquitetura e natureza."},
 {title:"Terraços profundos, sombra e privacidade",body:"O sol e as chuvas sazonais de Bali tornam os espaços externos cobertos essenciais. Os terraços projetados sombreiam os interiores envidraçados e separam visualmente as residências. A vegetação cria outro filtro entre ambientes privados e paisagem. Não são elementos apenas decorativos: influenciam conforto, vistas e a conexão cotidiana com o exterior."},
 {title:"Uma chegada fluida",body:"A entrada combina aberturas curvas, luz filtrada, névoa e plantas tropicais para criar uma transição gradual. Em vez de um lobby fechado convencional, a linguagem arquitetônica continua pelas áreas compartilhadas. A abertura central leva luz ao coração do pátio e dá identidade ao edifício, enquanto as texturas naturais reforçam a ligação com a paisagem de Nuanu."},
 {title:"Projetada para o clima tropical",body:"A arquitetura em Bali precisa responder à luz intensa, umidade e chuvas fortes. A imagem sob chuva mostra como grandes beirais e circulações protegidas favorecem o uso em diferentes condições. Drenagem, detalhes duráveis e manutenção são tão importantes quanto o conceito visual. Materiais finais e responsabilidades operacionais devem ser confirmados na documentação."},
 {title:"As vistas fazem parte da planta",body:"As perspectivas para oceano, rio e floresta são enquadradas pelos terraços desde o início. As vistas aérea e do pôr do sol mostram como o edifício acompanha a água e como cada nível se relaciona de modo diferente com o horizonte. Ao escolher uma unidade, compare orientação exata, profundidade do terraço, primeiro plano e distribuição interna."}
],captions:["Luna Residences ao pôr do sol junto ao rio","Fachada tropical em camadas e terraços verdes","Pátio de entrada com luz natural filtrada","Circulação protegida durante a chuva tropical","Terraços privativos voltados para a floresta","Terraços plantados diante do rio","Vista aérea de Luna Residences em Nuanu"]}}
export const architectureGuide=(locale:Locale)=>{const d=data[locale];return {...d,gallery:images.map((src,i)=>({src,alt:d.captions[i],caption:d.captions[i]}))}}
