import type {Locale} from "./site-data";
export const franceInvestmentSlug="invest-luna-residences-bali-from-france";
const content={
en:{title:"Invest in Luna Residences Bali from France",kicker:"REMOTE BUYER’S GUIDE",intro:"A practical guide for France-based buyers considering Luna Residences at Nuanu Creative City: remote discovery, documentation, payment milestones, projected returns and the checks to complete before committing.",related:"Prepare your Luna investment",sections:[
 {title:"Can the process begin without travelling to Bali?",body:"Yes. The discovery and comparison stages can be handled from France through video meetings, digital brochures, current availability, floor plans and unit-by-unit view information. Reservation and document review may also be organised remotely depending on the legal providers and identity checks involved. However, buyers should not assume that every signature can always be completed without travel. Confirm the exact signing, notarisation, power-of-attorney and compliance process for your circumstances before paying."},
 {title:"Is a French payslip required?",body:"A payslip is generally associated with a bank-financing application, not with a direct cash purchase from a developer. Luna’s published payment plan is a staged purchase schedule rather than a promise of mortgage approval. Buyers may still need to provide identification, address, source-of-funds and compliance documents. If financing is required, the lender sets its own income and credit requirements. Request the current document checklist before presenting the process as “without a payslip”."},
 {title:"How the published payment plan works",body:"The current project information presents four payment milestones: 25% at signing, 25% in the first quarter of 2027, 25% in the first quarter of 2028 and 25% at handover, currently indicated for the fourth quarter of 2028. Availability, prices, dates and contractual terms can change, so obtain the current reservation form and payment schedule for the selected residence. Also budget for legal advice, taxes, transfer costs and any operating charges."},
 {title:"Understanding the projected 10–14% ROI",body:"Luna’s marketing materials indicate a projected annual return of 10–14%. This is an illustration, not a guaranteed yield. Actual performance can vary with nightly rates, occupancy, management fees, maintenance, taxes, owner-use periods and market conditions. Ask for the full assumptions behind the projection and model conservative scenarios. A decision should remain viable even if revenue is lower or expenses are higher than the headline estimate."},
 {title:"Review the leasehold and legal pack",body:"Indonesian property rights differ from French freehold ownership. Luna is presented with a long-term leasehold structure. Before signing, instruct an independent Indonesian legal adviser to verify the contracting parties, land rights, lease duration, extension provisions, construction permissions, handover obligations and exit conditions. Indonesian Government Regulation No. 18 of 2021 also sets specific rules for residential property held by foreigners; the structure applicable to the selected unit must be confirmed professionally."},
 {title:"A six-step remote buyer checklist",body:"First, request the current dossier. Second, shortlist actual units by layout, view and intended use. Third, review the price, currency exposure and payment dates. Fourth, appoint independent legal and tax advisers in Indonesia and France. Fifth, verify all documents and projected operating costs before reservation. Sixth, sign only through the confirmed legal process and retain copies of every payment and agreement. The form below connects you with the Luna team for current project information."}
]},
fr:{title:"Investir à Luna Residences Bali depuis la France",kicker:"GUIDE DE L’ACHETEUR À DISTANCE",intro:"Un guide pratique pour investir depuis Paris ou ailleurs en France dans Luna Residences à Nuanu Creative City : processus à distance, documents, échéancier, rendement projeté et vérifications indispensables.",related:"Préparer votre investissement Luna",sections:[
 {title:"Peut-on commencer sans se déplacer à Bali ?",body:"Oui. La découverte et la comparaison peuvent être réalisées depuis la France par visioconférence, avec brochure numérique, disponibilités actualisées, plans et informations sur les vues de chaque unité. La réservation et l’étude des documents peuvent aussi être organisées à distance selon les contrôles d’identité et les intervenants juridiques. Il ne faut toutefois pas promettre que chaque signature sera toujours possible sans déplacement : mandat, légalisation et conformité doivent être confirmés pour votre situation avant tout paiement."},
 {title:"Faut-il fournir une fiche de paie française ?",body:"La fiche de paie concerne généralement une demande de financement bancaire, pas un achat direct financé sur fonds propres. L’échéancier publié par Luna est un plan de paiement du projet et ne constitue pas une promesse de crédit. Des justificatifs d’identité, de domicile, d’origine des fonds et de conformité peuvent néanmoins être demandés. Si vous sollicitez un financement, la banque fixe ses propres critères de revenus et de solvabilité. Demandez toujours la liste documentaire à jour."},
 {title:"Comprendre le plan de paiement publié",body:"Les informations actuelles présentent quatre échéances : 25 % à la signature, 25 % au premier trimestre 2027, 25 % au premier trimestre 2028 et 25 % à la livraison, actuellement indiquée au quatrième trimestre 2028. Disponibilités, prix, dates et clauses contractuelles pouvant évoluer, il faut obtenir l’échéancier correspondant à la résidence choisie. Prévoyez également conseil juridique, fiscalité, frais de transfert et charges d’exploitation."},
 {title:"Interpréter le ROI projeté de 10–14 %",body:"Les supports marketing de Luna présentent un rendement annuel projeté de 10 à 14 %. Il s’agit d’une illustration, jamais d’un rendement garanti. La performance réelle dépend des tarifs, de l’occupation, des frais de gestion, de l’entretien, des taxes, des périodes d’usage propriétaire et du marché. Demandez les hypothèses complètes et construisez des scénarios prudents. L’investissement doit rester cohérent même avec des revenus inférieurs ou des dépenses supérieures à l’estimation centrale."},
 {title:"Vérifier le leasehold et le dossier juridique",body:"Les droits immobiliers indonésiens diffèrent de la pleine propriété française. Luna est présenté avec une structure de leasehold longue durée. Avant de signer, mandatez un conseil juridique indonésien indépendant pour vérifier parties contractantes, droits sur le terrain, durée et extension du bail, autorisations, obligations de livraison et conditions de sortie. Le règlement gouvernemental indonésien n°18 de 2021 encadre aussi les logements détenus par des étrangers ; la structure exacte de l’unité doit être validée professionnellement."},
 {title:"Checklist en six étapes depuis la France",body:"Demandez d’abord le dossier actualisé. Sélectionnez ensuite des unités réelles selon plan, vue et usage. Vérifiez prix, exposition au change et échéances. Mandatez des conseils juridiques et fiscaux indépendants en Indonésie et en France. Contrôlez les documents et charges projetées avant réservation. Enfin, signez uniquement selon la procédure juridique confirmée et conservez chaque contrat et preuve de paiement. Le formulaire ci-dessous permet d’obtenir les informations actuelles de Luna."}
]},
es:{title:"Invertir en Luna Residences Bali desde Francia",kicker:"GUÍA DE COMPRA A DISTANCIA",intro:"Guía práctica para compradores residentes en Francia que estudian Luna Residences en Nuanu Creative City: proceso remoto, documentos, pagos, rentabilidad proyectada y controles previos.",related:"Prepara tu inversión en Luna",sections:[
 {title:"¿Se puede empezar sin viajar a Bali?",body:"Sí. La fase de descubrimiento puede realizarse desde Francia mediante videollamadas, dossier digital, disponibilidad, planos e información de vistas por unidad. La reserva y revisión documental también pueden organizarse a distancia según los controles de identidad y proveedores jurídicos. No debe suponerse que toda firma será siempre posible sin viajar: poderes, legalización y cumplimiento deben confirmarse para cada comprador antes de pagar."},
 {title:"¿Hace falta una nómina francesa?",body:"La nómina suele relacionarse con una solicitud de financiación bancaria, no con una compra directa mediante fondos propios. El calendario de Luna es un plan de pagos del proyecto, no una promesa de hipoteca. Aun así pueden solicitarse identidad, domicilio, origen de fondos y documentos de cumplimiento. Si necesitas financiación, el banco definirá sus requisitos de ingresos y crédito. Solicita la lista documental vigente."},
 {title:"El calendario de pagos publicado",body:"La información actual presenta cuatro hitos: 25% a la firma, 25% en el primer trimestre de 2027, 25% en el primer trimestre de 2028 y 25% a la entrega, indicada actualmente para el cuarto trimestre de 2028. Disponibilidad, precios, fechas y contratos pueden cambiar. Obtén el calendario de la unidad elegida e incluye asesoría legal, impuestos, transferencias y costes operativos."},
 {title:"Cómo interpretar el ROI proyectado del 10–14%",body:"Los materiales comerciales indican una rentabilidad anual proyectada del 10 al 14%. Es una ilustración, no una garantía. El resultado real depende de tarifas, ocupación, gestión, mantenimiento, impuestos, uso del propietario y mercado. Solicita las hipótesis completas y calcula escenarios prudentes. La decisión debe seguir siendo viable con ingresos menores o gastos mayores que la estimación principal."},
 {title:"Revisa el leasehold y el expediente jurídico",body:"Los derechos inmobiliarios indonesios difieren de la propiedad plena francesa. Luna se presenta con un leasehold de larga duración. Antes de firmar, encarga a un abogado indonesio independiente verificar partes, derechos del terreno, plazo y extensiones, permisos, entrega y salida. El Reglamento del Gobierno de Indonesia n.º 18 de 2021 también establece reglas para viviendas de extranjeros; confirma profesionalmente la estructura exacta."},
 {title:"Checklist remoto en seis pasos",body:"Solicita el dossier actual, compara unidades reales, revisa precio y divisa, nombra asesores jurídicos y fiscales independientes en Indonesia y Francia, verifica documentos y costes antes de reservar y firma únicamente mediante el proceso legal confirmado. Conserva todos los contratos y comprobantes. El formulario inferior permite solicitar la información actual de Luna."}
]},
pt:{title:"Investir em Luna Residences Bali a partir da França",kicker:"GUIA DE COMPRA REMOTA",intro:"Guia prático para compradores residentes na França que consideram Luna Residences em Nuanu Creative City: processo remoto, documentos, pagamentos, retorno projetado e verificações.",related:"Prepare seu investimento em Luna",sections:[
 {title:"É possível começar sem viajar para Bali?",body:"Sim. A descoberta pode ser feita da França por videochamadas, dossiê digital, disponibilidade, plantas e informações de vista por unidade. Reserva e análise de documentos também podem ser organizadas remotamente conforme verificações de identidade e prestadores jurídicos. Não se deve presumir que toda assinatura será sempre possível sem viagem: procuração, legalização e conformidade precisam ser confirmadas antes do pagamento."},
 {title:"É necessário apresentar holerite francês?",body:"O comprovante salarial geralmente se relaciona a financiamento bancário, não a compra direta com recursos próprios. O cronograma de Luna é um plano de pagamentos do projeto, não promessa de crédito. Ainda podem ser exigidos identidade, endereço, origem dos recursos e documentos de conformidade. Se houver financiamento, o banco define requisitos de renda e crédito. Solicite a lista documental atual."},
 {title:"Como funciona o plano de pagamento",body:"As informações atuais apresentam quatro etapas: 25% na assinatura, 25% no primeiro trimestre de 2027, 25% no primeiro trimestre de 2028 e 25% na entrega, atualmente indicada para o quarto trimestre de 2028. Disponibilidade, preços, datas e contratos podem mudar. Obtenha o cronograma da unidade escolhida e considere assessoria jurídica, impostos, transferências e custos operacionais."},
 {title:"Entenda o ROI projetado de 10–14%",body:"Os materiais comerciais indicam retorno anual projetado de 10 a 14%. É uma ilustração, não garantia. O resultado real depende de diárias, ocupação, gestão, manutenção, impostos, uso pelo proprietário e mercado. Solicite as premissas completas e modele cenários prudentes. A decisão deve continuar coerente mesmo com receitas menores ou despesas maiores que a estimativa principal."},
 {title:"Revise o leasehold e os documentos jurídicos",body:"Os direitos imobiliários indonésios diferem da propriedade plena francesa. Luna é apresentado com leasehold de longo prazo. Antes de assinar, contrate advogado indonésio independente para verificar partes, direitos sobre o terreno, duração, extensões, licenças, entrega e saída. O Regulamento do Governo da Indonésia nº 18 de 2021 também define regras para residências de estrangeiros; confirme a estrutura aplicável."},
 {title:"Checklist remoto em seis etapas",body:"Solicite o dossiê atual, compare unidades reais, revise preço e câmbio, contrate assessores jurídicos e fiscais independentes na Indonésia e França, confira documentos e custos antes da reserva e assine somente pelo processo legal confirmado. Guarde contratos e comprovantes. O formulário abaixo permite solicitar as informações atuais de Luna."}
]}}
export const franceInvestmentGuide=(locale:Locale)=>content[locale];
