import type {Locale} from "./site-data";

export const internationalInvestmentSlugs = [
  "invest-luna-residences-bali-from-abroad",
  "invest-luna-residences-bali-from-france",
  "invest-luna-residences-bali-from-spain",
  "invest-luna-residences-bali-from-portugal",
  "invest-luna-residences-bali-from-united-kingdom",
  "invest-luna-residences-bali-from-uae",
  "invest-luna-residences-bali-from-switzerland",
  "invest-luna-residences-bali-from-belgium",
] as const;
export type InternationalInvestmentSlug=(typeof internationalInvestmentSlugs)[number];

type Guide={title:string;kicker:string;intro:string;related:string;sections:{title:string;body:string}[]};

const marketFacts:Record<Exclude<InternationalInvestmentSlug,"invest-luna-residences-bali-from-abroad">,{country:Record<Locale,string>;cities:Record<Locale,string>;currency:string;time:string;usage:Record<Locale,string>;note:Record<Locale,string>}>= {
 "invest-luna-residences-bali-from-france":{country:{en:"France",fr:"la France",es:"Francia",pt:"França"},cities:{en:"Paris, Lyon, Nice and Bordeaux",fr:"Paris, Lyon, Nice et Bordeaux",es:"París, Lyon, Niza y Burdeos",pt:"Paris, Lyon, Nice e Bordéus"},currency:"EUR / USD",time:"6–7 h",usage:{en:"a second home, seasonal stays or a professionally managed rental",fr:"une résidence secondaire, des séjours saisonniers ou une location gérée",es:"una segunda residencia, estancias de temporada o alquiler gestionado",pt:"segunda residência, estadias sazonais ou locação gerida"},note:{en:"French residents should obtain advice on foreign-asset reporting, rental income and succession before signing.",fr:"Les résidents français doivent faire vérifier la déclaration d’actifs étrangers, les revenus locatifs et la succession avant signature.",es:"Los residentes franceses deben verificar la declaración de activos extranjeros, ingresos por alquiler y sucesión.",pt:"Residentes franceses devem verificar declaração de ativos estrangeiros, renda de locação e sucessão."}},
 "invest-luna-residences-bali-from-spain":{country:{en:"Spain",fr:"l’Espagne",es:"España",pt:"Espanha"},cities:{en:"Madrid, Barcelona, Valencia and Marbella",fr:"Madrid, Barcelone, Valence et Marbella",es:"Madrid, Barcelona, Valencia y Marbella",pt:"Madrid, Barcelona, Valência e Marbella"},currency:"EUR / USD",time:"6–7 h",usage:{en:"winter stays, lifestyle use or managed hospitality rental",fr:"des séjours hivernaux, un usage lifestyle ou une location hôtelière gérée",es:"estancias de invierno, uso personal o alquiler turístico gestionado",pt:"estadias de inverno, uso pessoal ou locação hoteleira gerida"},note:{en:"Bali leasehold and managed hospitality are not equivalent to Spanish residential tenancy. Claims about eliminating okupas or non-payment risk would be misleading: contracts, operator terms and enforcement still require independent review.",fr:"Le leasehold balinais et la gestion hôtelière ne sont pas comparables à la location résidentielle espagnole. Affirmer qu’ils suppriment tout risque d’occupation ou d’impayé serait trompeur : contrats, opérateur et recours doivent être vérifiés.",es:"El leasehold balinés y la gestión hotelera no equivalen al alquiler residencial español. Sería engañoso prometer que eliminan okupas o impagos: contratos, operador y vías de recurso requieren revisión independiente.",pt:"O leasehold balinês e a gestão hoteleira não equivalem ao arrendamento residencial espanhol. Não se pode prometer ausência de ocupação ou inadimplência: contratos e meios de recurso exigem análise."}},
 "invest-luna-residences-bali-from-portugal":{country:{en:"Portugal",fr:"le Portugal",es:"Portugal",pt:"Portugal"},cities:{en:"Lisbon, Porto, Cascais and the Algarve",fr:"Lisbonne, Porto, Cascais et l’Algarve",es:"Lisboa, Oporto, Cascais y el Algarve",pt:"Lisboa, Porto, Cascais e Algarve"},currency:"EUR / USD",time:"7–8 h",usage:{en:"long winter stays, remote work or professionally managed rental",fr:"de longs séjours d’hiver, le télétravail ou une location gérée",es:"largas estancias de invierno, teletrabajo o alquiler gestionado",pt:"estadias longas no inverno, trabalho remoto ou locação gerida"},note:{en:"Portuguese residents should verify overseas property, rental-income and capital-gain treatment with advisers in both jurisdictions.",fr:"Les résidents portugais doivent vérifier le traitement du bien étranger, des loyers et de la plus-value dans les deux juridictions.",es:"Los residentes portugueses deben revisar el tratamiento del inmueble extranjero, rentas y plusvalías en ambas jurisdicciones.",pt:"Residentes portugueses devem confirmar o tratamento do imóvel no exterior, rendimentos e mais-valias nas duas jurisdições."}},
 "invest-luna-residences-bali-from-united-kingdom":{country:{en:"the United Kingdom",fr:"le Royaume-Uni",es:"Reino Unido",pt:"Reino Unido"},cities:{en:"London, Manchester, Edinburgh and Birmingham",fr:"Londres, Manchester, Édimbourg et Birmingham",es:"Londres, Manchester, Edimburgo y Birmingham",pt:"Londres, Manchester, Edimburgo e Birmingham"},currency:"GBP / USD / IDR",time:"7–8 h",usage:{en:"a lifestyle base, extended escapes or operated short-stay accommodation",fr:"un pied-à-terre lifestyle, de longs séjours ou un hébergement courte durée exploité",es:"una base de estilo de vida, largas escapadas o alojamiento de corta estancia gestionado",pt:"uma base de lifestyle, estadias prolongadas ou hospedagem de curta duração gerida"},note:{en:"UK residents should check foreign income, capital gains, inheritance and currency exposure. Tax residence and domicile circumstances can materially change the answer.",fr:"Les résidents britanniques doivent vérifier revenus étrangers, plus-values, succession et change. Résidence fiscale et domicile peuvent modifier le traitement.",es:"Los residentes británicos deben revisar ingresos extranjeros, plusvalías, herencia y divisa. Residencia fiscal y domicilio pueden cambiar el resultado.",pt:"Residentes britânicos devem verificar rendimentos externos, ganhos de capital, herança e câmbio. Residência fiscal e domicílio alteram o tratamento."}},
 "invest-luna-residences-bali-from-uae":{country:{en:"the United Arab Emirates",fr:"les Émirats arabes unis",es:"Emiratos Árabes Unidos",pt:"Emirados Árabes Unidos"},cities:{en:"Dubai, Abu Dhabi and Sharjah",fr:"Dubaï, Abou Dhabi et Sharjah",es:"Dubái, Abu Dabi y Sharjah",pt:"Dubai, Abu Dhabi e Sharjah"},currency:"AED / USD / IDR",time:"4 h",usage:{en:"weekend-to-seasonal escapes, portfolio diversification or managed hospitality use",fr:"des séjours ponctuels ou saisonniers, une diversification ou un usage hôtelier géré",es:"escapadas o temporadas, diversificación o uso hotelero gestionado",pt:"escapadas ou temporadas, diversificação ou uso hoteleiro gerido"},note:{en:"The AED’s USD peg can simplify price comparison, but it does not remove IDR operating exposure or investment risk. UAE tax residence and reporting should still be confirmed for each buyer.",fr:"L’ancrage de l’AED au dollar facilite la comparaison, sans supprimer l’exposition opérationnelle à l’IDR ni le risque. Résidence fiscale et obligations aux EAU restent à confirmer.",es:"La paridad del AED con el dólar facilita comparar precios, pero no elimina la exposición operativa a IDR ni el riesgo. La residencia fiscal debe confirmarse.",pt:"A paridade do AED com o dólar facilita comparar preços, mas não elimina exposição ao IDR nem risco. A residência fiscal deve ser confirmada."}},
 "invest-luna-residences-bali-from-switzerland":{country:{en:"Switzerland",fr:"la Suisse",es:"Suiza",pt:"Suíça"},cities:{en:"Geneva, Zurich, Lausanne and Basel",fr:"Genève, Zurich, Lausanne et Bâle",es:"Ginebra, Zúrich, Lausana y Basilea",pt:"Genebra, Zurique, Lausanne e Basileia"},currency:"CHF / USD / IDR",time:"6–7 h",usage:{en:"a warm-season counterpart, extended stays or a managed international asset",fr:"un complément climatique, de longs séjours ou un actif international géré",es:"un complemento climático, largas estancias o un activo internacional gestionado",pt:"um complemento climático, estadias longas ou um ativo internacional gerido"},note:{en:"Swiss taxation varies by canton. Wealth tax, foreign income, valuation, succession and exchange-rate treatment should be checked in the buyer’s canton.",fr:"La fiscalité suisse varie selon le canton. Impôt sur la fortune, revenu étranger, valorisation, succession et change doivent être vérifiés dans le canton de l’acquéreur.",es:"La fiscalidad suiza varía por cantón. Patrimonio, ingresos extranjeros, valoración, sucesión y cambio deben revisarse localmente.",pt:"A tributação suíça varia por cantão. Patrimônio, renda externa, avaliação, sucessão e câmbio devem ser analisados localmente."}},
 "invest-luna-residences-bali-from-belgium":{country:{en:"Belgium",fr:"la Belgique",es:"Bélgica",pt:"Bélgica"},cities:{en:"Brussels, Antwerp, Ghent and Liège",fr:"Bruxelles, Anvers, Gand et Liège",es:"Bruselas, Amberes, Gante y Lieja",pt:"Bruxelas, Antuérpia, Gante e Liège"},currency:"EUR / USD",time:"6–7 h",usage:{en:"holiday use, longer remote stays or professionally managed rental",fr:"un usage vacances, de longs séjours à distance ou une location gérée",es:"uso vacacional, estancias remotas largas o alquiler gestionado",pt:"uso de férias, estadias remotas longas ou locação gerida"},note:{en:"Belgian residents should verify foreign-property declarations, cadastral treatment, rental income and inheritance according to their region and personal situation.",fr:"Les résidents belges doivent vérifier déclaration du bien étranger, traitement cadastral, revenus locatifs et succession selon leur région et leur situation.",es:"Los residentes belgas deben revisar declaración del inmueble extranjero, tratamiento catastral, alquiler y sucesión según su región.",pt:"Residentes belgas devem verificar declaração do imóvel externo, tratamento cadastral, renda e sucessão conforme a região."}}
};

const words={
 en:{hubTitle:"Invest in Luna Residences Bali from abroad",marketTitle:(c:string)=>`Invest in Luna Residences Bali from ${c}`,kicker:"INTERNATIONAL BUYER’S GUIDE",related:"Explore international buyer guides",remote:"A remote process, with deliberate checks",currency:"Currency and payment planning",time:"Time difference and communication",use:"Intended use shapes the unit choice",tax:"Tax and legal review",risk:"Returns: scenarios, never guarantees"},
 fr:{hubTitle:"Investir à Luna Residences Bali depuis l’étranger",marketTitle:(c:string)=>`Investir à Luna Residences Bali depuis ${c}`,kicker:"GUIDE DE L’ACHETEUR INTERNATIONAL",related:"Explorer les guides internationaux",remote:"Un parcours à distance, avec des contrôles précis",currency:"Devise et organisation des paiements",time:"Décalage horaire et communication",use:"L’usage prévu détermine le choix",tax:"Vérifications fiscales et juridiques",risk:"Rendement : des scénarios, jamais une garantie"},
 es:{hubTitle:"Invertir en Luna Residences Bali desde el extranjero",marketTitle:(c:string)=>`Invertir en Luna Residences Bali desde ${c}`,kicker:"GUÍA DEL COMPRADOR INTERNACIONAL",related:"Explorar las guías internacionales",remote:"Un proceso remoto con controles definidos",currency:"Divisa y planificación de pagos",time:"Diferencia horaria y comunicación",use:"El uso previsto orienta la elección",tax:"Revisión fiscal y jurídica",risk:"Rentabilidad: escenarios, nunca garantías"},
 pt:{hubTitle:"Investir no Luna Residences Bali a partir do exterior",marketTitle:(c:string)=>`Investir no Luna Residences Bali a partir de ${c}`,kicker:"GUIA DO COMPRADOR INTERNACIONAL",related:"Explorar os guias internacionais",remote:"Um processo remoto com controles claros",currency:"Moeda e planejamento de pagamentos",time:"Fuso horário e comunicação",use:"O uso pretendido orienta a escolha",tax:"Revisão fiscal e jurídica",risk:"Retorno: cenários, nunca garantias"}
} satisfies Record<Locale,any>;

export function internationalInvestmentGuide(locale:Locale,slug:InternationalInvestmentSlug):Guide{
 const w=words[locale];
 if(slug==="invest-luna-residences-bali-from-abroad") return {title:w.hubTitle,kicker:w.kicker,related:w.related,intro:{en:"A practical starting point for buyers outside Indonesia: compare seven key markets, prepare a remote purchase, understand currency exposure and commission independent legal and tax advice before committing.",fr:"Le point de départ des acquéreurs hors d’Indonésie : comparer sept marchés, préparer un achat à distance, comprendre le risque de change et mandater des conseils juridiques et fiscaux indépendants avant tout engagement.",es:"El punto de partida para compradores fuera de Indonesia: comparar siete mercados, preparar la compra a distancia, entender la exposición a divisas y obtener asesoría jurídica y fiscal independiente.",pt:"O ponto de partida para compradores fora da Indonésia: comparar sete mercados, preparar a compra remota, entender a exposição cambial e obter assessoria jurídica e fiscal independente."}[locale],sections:[
  {title:w.remote,body:{en:"Discovery can begin by video from Paris, Madrid, Lisbon, London, Dubai, Geneva or Brussels. Request current availability, floor plans, view orientation, the draft agreement, payment schedule and projected operating costs. Identity checks, notarisation or a power of attorney depend on the buyer and documents; confirm the exact signing route before transferring funds.",fr:"La découverte peut commencer en visioconférence depuis Paris, Madrid, Lisbonne, Londres, Dubaï, Genève ou Bruxelles. Demandez disponibilités, plans, orientation des vues, projet de contrat, échéancier et charges projetées. Contrôle d’identité, légalisation ou procuration dépendent du dossier : confirmez le parcours de signature avant tout virement.",es:"El proceso puede comenzar por vídeo desde París, Madrid, Lisboa, Londres, Dubái, Ginebra o Bruselas. Solicita disponibilidad, planos, orientación, borrador contractual, pagos y costes operativos. La identificación, legalización o poder dependen del caso: confirma la firma antes de transferir.",pt:"O processo pode começar por vídeo a partir de Paris, Madrid, Lisboa, Londres, Dubai, Genebra ou Bruxelas. Solicite disponibilidade, plantas, orientação, minuta, pagamentos e custos operacionais. Identificação, legalização ou procuração dependem do caso: confirme a assinatura antes de transferir."}[locale]},
  {title:w.currency,body:{en:"The asking currency, payment currency and eventual operating currency may differ. Compare the full acquisition cost in your home currency, model EUR, GBP, CHF or AED movements against USD and IDR, and agree banking fees and payment references in writing. Currency convenience is not the same as investment certainty.",fr:"Devise d’affichage, devise de paiement et devise d’exploitation peuvent différer. Calculez le coût complet dans votre devise, simulez les mouvements EUR, GBP, CHF ou AED face au USD et à l’IDR, puis confirmez frais bancaires et références de virement. La facilité de change ne garantit pas l’investissement.",es:"La moneda del precio, del pago y de la operación puede variar. Calcula el coste total en tu divisa, simula EUR, GBP, CHF o AED frente a USD e IDR y confirma gastos bancarios y referencias por escrito. La comodidad cambiaria no garantiza la inversión.",pt:"Moeda do preço, pagamento e operação podem diferir. Calcule o custo total na moeda local, simule EUR, GBP, CHF ou AED frente a USD e IDR e confirme taxas e referências bancárias. Facilidade cambial não garante o investimento."}[locale]},
  {title:w.tax,body:{en:"Indonesian leasehold, ownership vehicle, taxes, rental rules and succession require Indonesian advice. Your country of residence may also tax or require disclosure of foreign assets and income. Use independent professionals in both jurisdictions; sales material is not legal, tax or financial advice.",fr:"Leasehold indonésien, véhicule de détention, taxes, règles locatives et succession exigent un conseil indonésien. Le pays de résidence peut aussi imposer ou exiger la déclaration du bien et de ses revenus. Consultez des professionnels indépendants dans les deux juridictions.",es:"El leasehold indonesio, vehículo de tenencia, impuestos, alquiler y sucesión requieren asesoría indonesia. El país de residencia puede gravar o exigir declarar activos e ingresos extranjeros. Consulta profesionales independientes en ambas jurisdicciones.",pt:"Leasehold indonésio, veículo de titularidade, impostos, locação e sucessão exigem assessoria local. O país de residência pode tributar ou exigir declaração de ativos e rendas externas. Consulte profissionais independentes nas duas jurisdições."}[locale]},
  {title:w.use,body:{en:"Personal stays, family use, remote work and operated rental lead to different choices of layout, terrace, storage, view and management terms. Define your likely annual calendar first, then compare actual available units rather than selecting only from headline yield scenarios.",fr:"Séjours personnels, usage familial, télétravail et location exploitée conduisent à des choix différents de plan, terrasse, rangement, vue et gestion. Définissez votre calendrier annuel, puis comparez les unités réellement disponibles plutôt qu’un rendement mis en avant.",es:"Estancias personales, familia, teletrabajo y alquiler gestionado exigen diferentes planos, terrazas, almacenaje, vistas y gestión. Define tu calendario anual y compara unidades reales en lugar de elegir solo por una cifra de rentabilidad.",pt:"Estadias pessoais, família, trabalho remoto e locação gerida pedem plantas, terraços, armazenamento, vistas e gestão diferentes. Defina o calendário anual e compare unidades reais, não apenas uma taxa de retorno."}[locale]},
  {title:w.risk,body:{en:"Any return figure is an illustration based on assumptions about occupancy, nightly rates, operating expenses, taxes, management fees and currency. Ask for the complete assumptions and test conservative, base and optimistic cases. No ROI, resale price, occupancy or legal outcome is guaranteed.",fr:"Tout rendement est une illustration fondée sur l’occupation, les tarifs, charges, taxes, frais de gestion et change. Demandez toutes les hypothèses et testez des scénarios prudent, central et optimiste. Aucun ROI, prix de revente, taux d’occupation ou résultat juridique n’est garanti.",es:"Toda rentabilidad es una ilustración basada en ocupación, tarifas, gastos, impuestos, gestión y divisa. Solicita las hipótesis y prueba escenarios conservador, base y optimista. No se garantiza ROI, reventa, ocupación ni resultado jurídico.",pt:"Todo retorno é uma ilustração baseada em ocupação, diárias, custos, impostos, gestão e câmbio. Solicite as premissas e teste cenários conservador, base e otimista. ROI, revenda, ocupação ou resultado jurídico não são garantidos."}[locale]}
 ]};
 const f=marketFacts[slug];const country=f.country[locale];
 return {title:w.marketTitle(country),kicker:w.kicker,related:w.related,intro:{en:`A market-specific guide for buyers based in ${country}, including ${f.cities.en}: remote acquisition, ${f.currency} exposure, a typical ${f.time} time difference and the checks to complete before considering Luna Residences at Nuanu.`,fr:`Un guide adapté aux acquéreurs basés en ${country}, notamment à ${f.cities.fr} : achat à distance, exposition ${f.currency}, décalage d’environ ${f.time} et contrôles à effectuer avant d’envisager Luna Residences à Nuanu.`,es:`Guía adaptada a compradores en ${country}, especialmente ${f.cities.es}: compra remota, exposición ${f.currency}, diferencia habitual de ${f.time} y controles antes de considerar Luna Residences en Nuanu.`,pt:`Guia adaptado a compradores em ${country}, incluindo ${f.cities.pt}: compra remota, exposição ${f.currency}, diferença típica de ${f.time} e verificações antes de considerar o Luna Residences em Nuanu.`}[locale],sections:[
  {title:w.remote,body:{en:`From ${f.cities.en}, the first stages can be completed by video: project presentation, live availability, floor-plan comparison, view orientation and document collection. Before paying, confirm identity checks, reservation terms, signing formalities and whether any original, notarised or legalised document is required. “Remote” means organised at distance, not without documentation.`,fr:`Depuis ${f.cities.fr}, les premières étapes peuvent se faire en visioconférence : présentation, disponibilités en direct, comparaison des plans, orientation des vues et collecte des documents. Avant paiement, confirmez identité, réservation, signatures et éventuels originaux légalisés. « À distance » ne signifie pas sans justificatifs.`,es:`Desde ${f.cities.es}, las primeras etapas pueden hacerse por vídeo: presentación, disponibilidad, planos, orientación y documentos. Antes de pagar, confirma identificación, reserva, firma y posibles originales notarizados o legalizados. “A distancia” no significa sin documentación.`,pt:`A partir de ${f.cities.pt}, as primeiras etapas podem ser feitas por vídeo: apresentação, disponibilidade, plantas, orientação e documentos. Antes de pagar, confirme identidade, reserva, assinatura e eventuais originais legalizados. “Remoto” não significa sem documentação.`}[locale]},
  {title:w.currency,body:{en:`Model the complete acquisition in ${f.currency}, including transfer fees, exchange spreads, Indonesian operating costs and payment dates. Obtain written payment instructions and verify beneficiary details independently before every transfer. A favourable exchange rate can change; it should not be treated as a return.`,fr:`Modélisez le coût complet en ${f.currency}, avec frais de virement, marge de change, charges indonésiennes et dates d’échéance. Obtenez les instructions par écrit et vérifiez le bénéficiaire indépendamment avant chaque transfert. Un taux de change favorable n’est pas un rendement.`,es:`Calcula el coste completo en ${f.currency}, incluidos transferencias, cambio, costes indonesios y fechas. Obtén instrucciones por escrito y verifica al beneficiario antes de cada envío. Un cambio favorable no es rentabilidad.`,pt:`Calcule o custo completo em ${f.currency}, incluindo transferências, câmbio, custos indonésios e datas. Obtenha instruções por escrito e verifique o beneficiário antes de cada envio. Câmbio favorável não é retorno.`}[locale]},
  {title:w.time,body:{en:`The usual time difference with Bali is about ${f.time}, depending on city and daylight-saving time. A practical process uses scheduled video calls, a shared checklist, written meeting summaries and clear response deadlines across time zones. Record which adviser is responsible for each legal, tax, banking and project question.`,fr:`Le décalage habituel avec Bali est d’environ ${f.time}, selon la ville et l’heure d’été. Prévoyez visioconférences planifiées, checklist partagée, comptes rendus écrits et délais clairs. Identifiez le conseiller responsable de chaque question juridique, fiscale, bancaire et immobilière.`,es:`La diferencia habitual con Bali es de unos ${f.time}, según ciudad y horario de verano. Organiza videollamadas, lista compartida, resúmenes escritos y plazos claros. Define quién responde cada cuestión jurídica, fiscal, bancaria y del proyecto.`,pt:`A diferença habitual com Bali é de cerca de ${f.time}, conforme cidade e horário de verão. Organize videochamadas, checklist compartilhado, resumos escritos e prazos claros. Defina quem responde por cada questão jurídica, fiscal, bancária e do projeto.`}[locale]},
  {title:w.use,body:{en:`Buyers in ${country} often compare ${f.usage.en}. Each objective changes the suitable unit, personal-use calendar, furnishing, management agreement and cash-flow assumptions. Ask for actual unit-level availability and operating terms before building a financial scenario.`,fr:`Les acquéreurs basés en ${country} comparent souvent ${f.usage.fr}. Chaque objectif modifie unité, calendrier d’usage, mobilier, contrat de gestion et hypothèses de trésorerie. Demandez disponibilités et conditions d’exploitation par unité avant toute simulation.`,es:`Los compradores en ${country} suelen comparar ${f.usage.es}. Cada objetivo cambia unidad, calendario, mobiliario, gestión y flujo de caja. Solicita disponibilidad y condiciones reales por unidad antes de modelizar.`,pt:`Compradores em ${country} costumam comparar ${f.usage.pt}. Cada objetivo muda unidade, calendário, mobiliário, gestão e fluxo de caixa. Solicite disponibilidade e condições reais por unidade antes de projetar.`}[locale]},
  {title:w.tax,body:f.note[locale]},
  {title:w.risk,body:{en:"Request the assumptions behind any projected performance: occupancy, rates, seasonality, management fees, maintenance, reserve funds, taxes and currency. Compare conservative, base and optimistic cases. No return, occupancy level, resale value, tax outcome or uninterrupted rental income is guaranteed.",fr:"Demandez les hypothèses de toute projection : occupation, tarifs, saisonnalité, gestion, entretien, réserve, taxes et change. Comparez scénarios prudent, central et optimiste. Aucun rendement, taux d’occupation, prix de revente, résultat fiscal ou revenu continu n’est garanti.",es:"Solicita las hipótesis de toda proyección: ocupación, tarifas, temporada, gestión, mantenimiento, reservas, impuestos y divisa. Compara escenarios conservador, base y optimista. No se garantiza retorno, ocupación, reventa, fiscalidad ni ingresos continuos.",pt:"Solicite as premissas de toda projeção: ocupação, tarifas, sazonalidade, gestão, manutenção, reservas, impostos e câmbio. Compare cenários conservador, base e otimista. Não há garantia de retorno, ocupação, revenda, tributação ou renda contínua."}[locale]}
 ]};
}
