import type { Locale } from "./site-data";
export const nyanyiSlug="nyanyi-beach-nuanu-area-guide";
const content={
en:{title:"Nyanyi Beach and Nuanu: a coastal area guide",kicker:"NYANYI BEACH AREA GUIDE",intro:"Nyanyi Beach offers a quieter coastal rhythm beside Nuanu Creative City. This guide looks at the landscape, daily life and practical questions to explore when considering a home in this part of Bali.",related:"Explore Luna Residences",sections:[
 {title:"The character of Nyanyi Beach",body:"Nyanyi Beach is defined by a broad volcanic-sand shoreline, open ocean views and a less urban atmosphere than Bali’s busiest beach districts. The experience changes with the tide and weather, so prospective residents should visit at different times of day rather than rely on a single photograph. The coast invites walking, watching sunsets and slowing down, while the surrounding landscape retains a strong relationship with rivers, fields and tropical planting."},
 {title:"Living beside Nuanu Creative City",body:"Nuanu adds a cultural and social layer to the coastal setting. Its mix of art, food, wellness, education and events means that living nearby is not only about beach access. Residents can combine private time at home with places to meet, learn and recharge. Luna Residences sits within this environment, making the wider destination part of everyday life rather than an occasional excursion. Explore the Nuanu page to understand how the different venues fit together."},
 {title:"What everyday convenience means here",body:"A good area assessment should go beyond headline travel times. Map the routes you would use for food, school, wellness, work and airport journeys, then consider how traffic and weather may change them. Check mobile coverage, internet arrangements, transport options and the services included with a residence. Within a managed project, reception, maintenance and local assistance can simplify daily life, but the exact service scope should always be confirmed before purchase."},
 {title:"Nature, climate and coastal comfort",body:"Coastal Bali brings strong light, humidity, salt air and seasonal rain. Architecture and operations therefore matter: shaded outdoor areas, ventilation, planting, drainage and regular maintenance all support comfort. When comparing a residence, ask how terraces are protected, how common landscaping is cared for and how interiors are managed between stays. These questions are particularly important for owners who will spend part of the year abroad or make the home available for managed rentals."},
 {title:"How to evaluate the area for your plans",body:"Visit with your intended use in mind. A personal retreat, a family base and a managed rental each create a different shortlist. Compare unit layouts and views, but also walk the surrounding destination and imagine a normal weekday rather than only a holiday. Request current plans, availability, operating details and the legal pack, then obtain independent professional advice before committing funds. The form below provides direct access to the latest Luna Residences dossier."}
]},
fr:{title:"Nyanyi Beach et Nuanu : guide du quartier",kicker:"GUIDE DE NYANYI BEACH",intro:"Nyanyi Beach offre un rythme côtier plus paisible aux portes de Nuanu Creative City. Ce guide présente le paysage, la vie quotidienne et les points à examiner avant d’envisager une résidence dans cette partie de Bali.",related:"Découvrir Luna Residences",sections:[
 {title:"Le caractère de Nyanyi Beach",body:"Nyanyi Beach se distingue par une grande plage de sable volcanique, un horizon ouvert et une ambiance moins urbaine que les zones balnéaires les plus fréquentées de Bali. Le paysage évolue avec la marée et la météo : il est donc préférable de visiter à plusieurs heures plutôt que de se fier à une seule image. Le littoral invite à marcher et à observer le coucher du soleil, dans un environnement encore lié aux rivières, aux champs et à la végétation tropicale."},
 {title:"Vivre aux côtés de Nuanu Creative City",body:"Nuanu apporte une dimension culturelle et sociale au cadre côtier. Art, restauration, bien-être, éducation et événements permettent de vivre le quartier au-delà de la plage. Les résidents peuvent alterner intimité chez eux et lieux où se rencontrer, apprendre ou se ressourcer. Luna Residences s’inscrit dans cet environnement : la destination devient une partie du quotidien plutôt qu’une sortie occasionnelle. La page consacrée à Nuanu détaille cet écosystème."},
 {title:"Évaluer la praticité au quotidien",body:"Une bonne étude du quartier dépasse les temps de trajet annoncés. Repérez les parcours vers les commerces, l’école, les espaces de bien-être, le travail et l’aéroport, puis tenez compte du trafic et de la météo. Vérifiez la couverture mobile, la connexion internet, les transports et les services inclus avec la résidence. Dans un projet géré, réception, maintenance et assistance locale peuvent simplifier la vie, mais leur périmètre exact doit être confirmé avant l’achat."},
 {title:"Nature, climat et confort côtier",body:"Le littoral balinais combine lumière intense, humidité, air salin et pluies saisonnières. L’architecture et la gestion sont donc essentielles : ombrage, ventilation, végétation, drainage et entretien régulier favorisent le confort. En comparant les résidences, demandez comment les terrasses sont protégées, comment les jardins communs sont entretenus et comment les intérieurs sont suivis entre deux séjours, surtout si vous vivez une partie de l’année à l’étranger."},
 {title:"Adapter le quartier à votre projet",body:"Visitez avec votre usage en tête. Une retraite personnelle, une base familiale et une location gérée ne produisent pas la même sélection. Comparez les plans et les vues, mais parcourez aussi la destination en imaginant un jour ordinaire. Demandez les disponibilités, les modalités de gestion et le dossier juridique, puis consultez des professionnels indépendants avant tout engagement financier. Le formulaire ci-dessous donne accès au dossier Luna Residences actualisé."}
]},
es:{title:"Nyanyi Beach y Nuanu: guía de la zona",kicker:"GUÍA DE NYANYI BEACH",intro:"Nyanyi Beach ofrece un ritmo costero tranquilo junto a Nuanu Creative City. Esta guía recorre el paisaje, la vida diaria y las preguntas prácticas que conviene plantear antes de elegir una vivienda en esta parte de Bali.",related:"Descubre Luna Residences",sections:[
 {title:"El carácter de Nyanyi Beach",body:"Nyanyi Beach se distingue por su extensa playa de arena volcánica, vistas abiertas al océano y una atmósfera menos urbana que las zonas costeras más concurridas de Bali. El paisaje cambia con la marea y el tiempo, por lo que conviene visitar a distintas horas y no depender de una sola fotografía. La costa invita a caminar y contemplar el atardecer, mientras el entorno conserva su relación con ríos, campos y vegetación tropical."},
 {title:"Vivir junto a Nuanu Creative City",body:"Nuanu añade una dimensión cultural y social al entorno costero. Arte, gastronomía, bienestar, educación y eventos hacen que vivir cerca no dependa únicamente de la playa. Los residentes pueden combinar privacidad con lugares para reunirse, aprender y descansar. Luna Residences se integra en este entorno, convirtiendo el destino en parte de la vida diaria. La página dedicada a Nuanu explica cómo se relacionan sus diferentes espacios."},
 {title:"Comodidad en la vida diaria",body:"Una evaluación útil debe superar los tiempos de viaje promocionales. Recorre las rutas hacia comida, colegio, bienestar, trabajo y aeropuerto, y considera cómo cambian con el tráfico y la lluvia. Comprueba cobertura móvil, internet, transporte y servicios incluidos. En un proyecto gestionado, recepción, mantenimiento y asistencia local pueden simplificar el día a día, pero es importante confirmar exactamente qué cubre cada servicio antes de comprar."},
 {title:"Naturaleza, clima y confort",body:"La costa de Bali combina luz intensa, humedad, aire salino y lluvia estacional. Por eso importan la arquitectura y la operación: sombra, ventilación, vegetación, drenaje y mantenimiento regular favorecen el confort. Al comparar una residencia, pregunta cómo se protegen las terrazas, cómo se cuidan los jardines comunes y cómo se gestiona el interior entre estancias, especialmente si pasarás parte del año fuera de Bali."},
 {title:"Evaluar la zona según tu objetivo",body:"Visita pensando en el uso previsto. Un refugio personal, una base familiar y un alquiler gestionado generan prioridades distintas. Compara planos y vistas, pero recorre también el destino imaginando un día normal. Solicita disponibilidad, detalles operativos y documentación jurídica, y busca asesoramiento profesional independiente antes de comprometer fondos. El formulario inferior permite pedir el dossier actualizado de Luna Residences."}
]},
pt:{title:"Nyanyi Beach e Nuanu: guia da região",kicker:"GUIA DE NYANYI BEACH",intro:"Nyanyi Beach oferece um ritmo costeiro tranquilo ao lado de Nuanu Creative City. Este guia apresenta a paisagem, a rotina e as questões práticas a considerar antes de escolher uma residência nesta parte de Bali.",related:"Conheça Luna Residences",sections:[
 {title:"O caráter de Nyanyi Beach",body:"Nyanyi Beach é marcada por uma extensa faixa de areia vulcânica, vistas abertas para o oceano e uma atmosfera menos urbana do que os distritos costeiros mais movimentados de Bali. A paisagem muda com a maré e o clima, por isso vale visitar em diferentes horários em vez de confiar em uma única imagem. A costa convida a caminhar e observar o pôr do sol, cercada por rios, campos e vegetação tropical."},
 {title:"Viver ao lado de Nuanu Creative City",body:"Nuanu acrescenta uma dimensão cultural e social ao cenário costeiro. Arte, gastronomia, bem-estar, educação e eventos fazem com que morar perto seja mais do que ter acesso à praia. Os residentes podem combinar privacidade com lugares para encontrar pessoas, aprender e descansar. Luna Residences faz parte desse ambiente, tornando o destino presente no cotidiano. A página sobre Nuanu mostra como seus diferentes espaços se conectam."},
 {title:"Conveniência na rotina",body:"Uma boa análise da região vai além dos tempos de deslocamento divulgados. Percorra as rotas para alimentação, escola, bem-estar, trabalho e aeroporto, considerando trânsito e chuva. Verifique cobertura móvel, internet, transporte e serviços incluídos. Em um projeto administrado, recepção, manutenção e assistência local podem facilitar o dia a dia, mas o escopo exato de cada serviço deve ser confirmado antes da compra."},
 {title:"Natureza, clima e conforto costeiro",body:"A costa de Bali combina luz intensa, umidade, maresia e chuvas sazonais. Arquitetura e operação são importantes: sombra, ventilação, paisagismo, drenagem e manutenção regular favorecem o conforto. Ao comparar uma residência, pergunte como os terraços são protegidos, como os jardins comuns são cuidados e como os interiores são administrados entre estadias, sobretudo se você passar parte do ano fora de Bali."},
 {title:"Avaliar a região para seus planos",body:"Visite pensando no uso pretendido. Um refúgio pessoal, uma base familiar e uma locação administrada geram prioridades diferentes. Compare plantas e vistas, mas percorra o destino imaginando um dia comum. Solicite disponibilidade, detalhes operacionais e documentação jurídica, buscando aconselhamento profissional independente antes de comprometer recursos. O formulário abaixo permite pedir o dossiê atualizado de Luna Residences."}
]}}
export const nyanyiGuide=(locale:Locale)=>content[locale];
