import type { Locale } from "./site-data";
export const slug="ocean-view-residences-bali-guide";
const sections={
en:[
 ["Start with the quality of the view","A sea view is more than a line on a brochure. Compare the outlook from the living room, bedroom and terrace, then consider what sits in the foreground. River corridors, mature planting and changes in elevation can add depth and privacy. Ask for the exact unit position and review plans alongside current visual material. At Luna Residences, typologies are arranged around ocean, river and jungle outlooks, so the right choice begins with the atmosphere you want every day."],
 ["Study orientation, light and shade","Bali’s tropical light changes throughout the day. Orientation affects morning brightness, afternoon heat, glare and outdoor comfort. Generous overhangs, shaded terraces, cross-ventilation and planting can make a meaningful difference. Look beyond the headline view and ask how sunlight reaches the interior. A balanced design should frame the horizon while keeping bedrooms, living areas and terraces comfortable across seasons."],
 ["Compare terraces and everyday living","The most valuable view is one you can enjoy naturally. Check whether the terrace connects directly to the principal living space, whether furniture can be arranged without blocking circulation, and how much privacy exists between neighbouring units. Also compare storage, kitchen usability and bedroom separation. Luna’s collection ranges from efficient studios to one-bedroom suites and larger family residences."],
 ["Understand the wider setting","A coastal home is shaped by its neighbourhood. Consider access to dining, wellness, culture, education and places to meet, as well as the route to the beach. Luna Residences sits within Nuanu Creative City near Nyanyi Beach, connecting a private home with a broader lifestyle ecosystem. For personal use this can make daily life easier; for rental use, a distinctive destination helps guests understand the area."],
 ["Review operations and long-term care","Salt air, humidity and tropical rain make maintenance important in coastal Bali. Ask who manages common areas, how residences are cared for between stays and which operating costs apply. If rental management is offered, review the service scope, owner-use rules and reporting process. Any return forecast is illustrative rather than guaranteed. Independent legal and financial advice remains essential before signing or transferring funds."],
 ["Build a unit-by-unit shortlist","Compare actual available units: current floor plans, view directions, terrace sizes, price and payment milestones. Create a shortlist based on intended use—compact and efficient for occasional stays, more separation for longer visits, or additional bedrooms for family use. The Luna Residences team can provide the latest brochure and availability through the form below."]],
fr:[
 ["Évaluer la qualité réelle de la vue","Une vue mer ne se résume pas à une mention sur une brochure. Comparez ce que l’on voit depuis le séjour, la chambre et la terrasse, puis observez le premier plan. Une rivière, une végétation mature ou une différence de niveau peuvent apporter profondeur et intimité. Demandez la position exacte de l’unité et confrontez les plans aux visuels disponibles. À Luna Residences, les logements s’ouvrent sur l’océan, la rivière ou la jungle."],
 ["Observer l’orientation, la lumière et l’ombre","La lumière tropicale de Bali évolue fortement dans la journée. L’orientation influence la luminosité du matin, la chaleur de l’après-midi, les reflets et le confort extérieur. Débords de toiture, terrasses ombragées, ventilation traversante et végétation jouent un rôle essentiel. Une conception équilibrée doit valoriser l’horizon tout en préservant le confort des chambres, du séjour et des terrasses."],
 ["Comparer les terrasses et les usages","La meilleure vue est celle dont on profite naturellement. Vérifiez la continuité entre terrasse et séjour, la place disponible pour le mobilier et l’intimité entre voisins. Comparez aussi les rangements, la cuisine et la séparation des chambres. La collection Luna va du studio optimisé aux suites une chambre et aux résidences familiales, afin d’arbitrer entre terrasse généreuse et espace intérieur."],
 ["Comprendre l’environnement du projet","Une résidence côtière dépend aussi de son quartier. Étudiez l’accès à la restauration, au bien-être, à la culture, à l’éducation et aux lieux de rencontre, ainsi que le parcours vers la plage. Luna Residences se trouve dans Nuanu Creative City, près de Nyanyi Beach, reliant l’habitat privé à un écosystème lifestyle plus large."],
 ["Vérifier la gestion et l’entretien","Air salin, humidité et pluies tropicales rendent l’entretien déterminant à Bali. Demandez qui gère les parties communes, comment le logement est suivi entre deux séjours et quelles charges s’appliquent. Si une gestion locative est proposée, examinez les services et les règles d’usage propriétaire. Toute projection de rendement reste indicative et non garantie. Un avis juridique et financier indépendant est indispensable."],
 ["Créer une sélection unité par unité","Demandez les plans actuels, l’orientation des vues, la taille des terrasses, les prix et les échéances. Classez les unités selon votre usage : format compact pour des séjours ponctuels, séparation accrue pour vivre plus longtemps ou chambres supplémentaires pour une famille. Le formulaire ci-dessous permet de recevoir la brochure et les disponibilités Luna."]],
es:[
 ["Valora la calidad real de la vista","Una vista al mar es más que una frase en un folleto. Compara lo que se ve desde el salón, el dormitorio y la terraza, y observa el primer plano. Un río, vegetación madura o cambios de altura aportan profundidad y privacidad. Solicita la posición exacta de la unidad y revisa los planos con el material visual disponible. En Luna Residences, las tipologías se orientan al océano, al río o a la selva."],
 ["Estudia orientación, luz y sombra","La luz tropical de Bali cambia durante el día. La orientación influye en la claridad de la mañana, el calor de la tarde, los reflejos y el confort exterior. Aleros amplios, terrazas sombreadas, ventilación cruzada y vegetación marcan una diferencia importante. Un buen diseño debe enmarcar el horizonte y mantener cómodos dormitorios, salones y terrazas."],
 ["Compara terrazas y vida cotidiana","La vista más valiosa es la que se disfruta con naturalidad. Comprueba la conexión entre terraza y salón, si el mobiliario cabe sin bloquear el paso y la privacidad entre unidades. Compara almacenamiento, cocina y separación de dormitorios. Luna incluye estudios eficientes, suites de un dormitorio y residencias familiares para equilibrar terraza y espacio interior."],
 ["Comprende el entorno","Considera el acceso a gastronomía, bienestar, cultura, educación y espacios sociales, además del camino a la playa. Luna Residences está en Nuanu Creative City, cerca de Nyanyi Beach, y conecta una vivienda privada con un ecosistema de estilo de vida más amplio. Para uso personal facilita el día a día; para alquiler, ayuda a explicar el atractivo de la zona."],
 ["Revisa operación y mantenimiento","El aire salino, la humedad y la lluvia tropical hacen esencial el mantenimiento. Pregunta quién gestiona las zonas comunes, cómo se cuida la residencia y qué costes se aplican. Si hay gestión de alquiler, revisa servicios y reglas de uso. Toda proyección de retorno es ilustrativa, no garantizada. Busca asesoramiento jurídico y financiero independiente."],
 ["Crea una lista por unidad","Solicita planos actuales, dirección de las vistas, tamaño de terrazas, precio e hitos de pago. Clasifica según tu uso: formato compacto para visitas puntuales, mayor separación para estancias largas o dormitorios extra para familias. El formulario inferior permite solicitar el dossier y la disponibilidad actual de Luna Residences."]],
pt:[
 ["Avalie a qualidade real da vista","Uma vista para o mar é mais do que uma frase no material comercial. Compare o cenário a partir da sala, do quarto e do terraço, observando o primeiro plano. Rio, vegetação madura e diferenças de nível podem acrescentar profundidade e privacidade. Peça a posição exata da unidade e analise plantas e visuais. Em Luna Residences, as tipologias se abrem para o oceano, o rio ou a floresta."],
 ["Estude orientação, luz e sombra","A luz tropical de Bali muda ao longo do dia. A orientação influencia a claridade da manhã, o calor da tarde, o brilho e o conforto externo. Beirais, terraços sombreados, ventilação cruzada e paisagismo fazem diferença. Um projeto equilibrado enquadra o horizonte e mantém quartos, salas e terraços confortáveis nas diferentes estações."],
 ["Compare terraços e rotina","A vista mais valiosa é aquela aproveitada naturalmente. Verifique a conexão entre terraço e sala, se os móveis cabem sem bloquear a circulação e a privacidade entre unidades. Compare armazenamento, cozinha e separação dos quartos. Luna vai de estúdios eficientes a suítes de um quarto e residências familiares, equilibrando terraço e área interna."],
 ["Entenda o entorno","Considere acesso a gastronomia, bem-estar, cultura, educação e espaços sociais, além do caminho até a praia. Luna Residences fica em Nuanu Creative City, perto de Nyanyi Beach, conectando a residência privada a um ecossistema de lifestyle mais amplo. Para uso pessoal, facilita o cotidiano; para locação, explica o atrativo da região."],
 ["Revise operação e manutenção","Ar salino, umidade e chuvas tropicais tornam a manutenção importante. Pergunte quem administra as áreas comuns, como a unidade é cuidada e quais custos se aplicam. Se houver gestão de locação, examine os serviços e regras de uso. Toda projeção de retorno é ilustrativa, não garantida. Procure aconselhamento jurídico e financeiro independente."],
 ["Monte uma seleção por unidade","Solicite plantas atuais, direção das vistas, tamanho dos terraços, preço e etapas de pagamento. Organize conforme o uso: formato compacto para visitas ocasionais, maior separação para estadias longas ou quartos adicionais para a família. O formulário abaixo permite solicitar o dossiê e a disponibilidade atual de Luna Residences."]]
};
const heads={en:["Ocean-view residences in Bali: a buyer’s guide","OCEAN-VIEW BUYER’S GUIDE","An ocean view can define a Bali residence, but the best choice also depends on orientation, landscape, privacy and everyday use.","Continue exploring Luna"],fr:["Résidence vue océan à Bali : guide d’achat","GUIDE VUE OCÉAN","Une vue sur l’océan peut définir une résidence à Bali, mais le bon choix dépend aussi de l’orientation, du paysage, de l’intimité et de votre usage.","Poursuivre votre découverte de Luna"],es:["Residencias con vista al océano en Bali: guía de compra","GUÍA DE VISTAS AL OCÉANO","Una vista al océano puede definir una residencia en Bali, pero la mejor elección también depende de la orientación, el paisaje, la privacidad y el uso previsto.","Sigue explorando Luna"],pt:["Residências com vista para o oceano em Bali: guia","GUIA DE VISTA PARA O OCEANO","Uma vista para o oceano pode definir uma residência em Bali, mas a melhor escolha também depende da orientação, paisagem, privacidade e forma de uso.","Continue conhecendo Luna"]};
export const guide=(locale:Locale)=>{const h=heads[locale];return {title:h[0],kicker:h[1],intro:h[2],related:h[3],sections:sections[locale].map(([title,body])=>({title,body}))}};
