export const locales = ["en", "fr", "es", "pt"] as const;
export type Locale = (typeof locales)[number];
export type PageKey = "residences" | "investment" | "nuanu" | "buying-guide";

export const baseUrl = "https://luna-residences-bali.palmdubai.chatgpt.site";

export const languageNames: Record<Locale, string> = { en: "EN", fr: "FR", es: "ES", pt: "PT" };

export const copy: Record<Locale, any> = {
  en: {
    nav: ["Project", "Residences", "Investment", "Nuanu"], brochure: "Get the brochure", hero: "Where the river|meets the ocean.", intro: "15 iconic residences by YODEZEEN. A rare collection shaped by tropical forest, culture and the horizon.", access: "Priority access", discover: "Discover Luna", from: "From", collection: "Collection", delivery: "Handover", vision: "The vision", visionTitle: "More than an address.|A new way to|live in Bali.", visionLead: "Luna Residences brings architecture, hospitality and nature together within Nuanu’s living ecosystem.", visionBody: "Every residence opens onto the ocean, river or jungle. YODEZEEN’s fluid lines extend the landscape while five-star hospitality takes care of every detail, 24/7.", essentials: "The essentials", roi: "Projected annual ROI*", lease: "Long-term leasehold", down: "Initial payment", beach: "From Nyanyi Beach", disclaimer: "*Illustrative projection, not guaranteed. Subject to occupancy, costs, market conditions and selected residence.", coll: "The collection", collTitle: "Five ways to live|at Luna’s rhythm.", collIntro: "From an intimate studio to the signature penthouse, every typology is designed around views, terraces and light.", lifestyle: "The Luna privilege", lifestyleTitle: "The beach club becomes|your everyday life.", lifestyleBody: "Luna Beach Club’s hospitality and creative energy extend all the way home.", nuanuTitle: "44 hectares.|A world of its own.", nuanuBody: "Art, dining, education, wellness and nature: Nuanu is a year-round coastal destination designed to create, learn and reconnect.", invest: "Investment", investTitle: "A rare asset.|Effortlessly managed.", investBody: "A very limited collection, a fast-growing destination and complete hotel-grade management bring personal use and rental potential together.", payment: "Payment plan", paymentTitle: "Move forward|at your pace.", faq: "Frequently asked questions", faqTitle: "Everything you need|to know.", contact: "Priority access", contactTitle: "The best views|go first.", contactBody: "Receive the brochure, floor plans, current price list and availability.", name: "Your name", phone: "WhatsApp / Phone", budget: "Budget", goal: "Your plan", select: "Select", consent: "I agree to be contacted about Luna Residences.", submit: "Get the complete dossier", response: "Personal reply within 24 hours", privacy: "No spam. Your information remains confidential.", footer: "INDICATIVE INFORMATION, SUBJECT TO AVAILABILITY.", pageTitles: {residences:"Residences & Floor Plans",investment:"Investment in Luna Residences",nuanu:"Living in Nuanu Creative City","buying-guide":"Buying Property in Bali"}, pageKickers:{residences:"THE COLLECTION",investment:"THE OPPORTUNITY",nuanu:"THE DESTINATION","buying-guide":"BUYER’S GUIDE"}
  },
  fr: {
    nav: ["Le projet", "Résidences", "Investir", "Nuanu"], brochure: "Recevoir la brochure", hero: "Là où la rivière|rencontre l’océan.", intro: "15 résidences iconiques signées YODEZEEN. Une collection rare entre jungle tropicale, culture et horizon.", access: "Accès prioritaire", discover: "Découvrir Luna", from: "À partir de", collection: "Collection", delivery: "Livraison", vision: "La vision", visionTitle: "Plus qu’une adresse.|Une nouvelle façon|d’habiter Bali.", visionLead: "Luna Residences réunit architecture, hospitalité et nature dans l’écosystème vivant de Nuanu.", visionBody: "Chaque résidence s’ouvre sur l’océan, la rivière ou la jungle. Les lignes fluides de YODEZEEN prolongent le paysage tandis qu’une gestion 5 étoiles prend soin de chaque détail, 24h/24.", essentials: "L’essentiel", roi: "Rendement annuel projeté*", lease: "Leasehold longue durée", down: "Premier apport", beach: "De la plage de Nyanyi", disclaimer: "*Projection indicative, non garantie. Selon occupation, charges, marché et résidence choisie.", coll: "La collection", collTitle: "Cinq façons de vivre|au rythme de Luna.", collIntro: "Du studio intime au penthouse signature, chaque typologie privilégie les vues, les terrasses et la lumière.", lifestyle: "Le privilège Luna", lifestyleTitle: "Le beach club devient|votre quotidien.", lifestyleBody: "L’hospitalité et l’énergie créative de Luna Beach Club se prolongent jusque chez vous.", nuanuTitle: "44 hectares.|Un monde en soi.", nuanuBody: "Art, gastronomie, éducation, bien-être et nature : Nuanu est une destination côtière vivante toute l’année.", invest: "L’investissement", investTitle: "Un actif rare.|Géré sans effort.", investBody: "Une collection très limitée, une destination en croissance et une gestion hôtelière complète réunissent usage personnel et potentiel locatif.", payment: "Plan de paiement", paymentTitle: "Avancez|à votre rythme.", faq: "Questions fréquentes", faqTitle: "Tout ce qu’il faut|savoir.", contact: "Accès prioritaire", contactTitle: "Les meilleures vues|partent en premier.", contactBody: "Recevez la brochure, les plans, les prix et les disponibilités actualisées.", name: "Votre nom", phone: "WhatsApp / Téléphone", budget: "Budget", goal: "Votre projet", select: "Sélectionner", consent: "J’accepte d’être contacté à propos de Luna Residences.", submit: "Recevoir le dossier complet", response: "Réponse personnalisée sous 24 h", privacy: "Aucun spam. Vos informations restent confidentielles.", footer: "INFORMATIONS INDICATIVES, SOUS RÉSERVE DE DISPONIBILITÉ.", pageTitles:{residences:"Résidences & plans",investment:"Investir à Luna Residences",nuanu:"Vivre à Nuanu Creative City","buying-guide":"Acheter un bien à Bali"}, pageKickers:{residences:"LA COLLECTION",investment:"L’OPPORTUNITÉ",nuanu:"LA DESTINATION","buying-guide":"GUIDE D’ACHAT"}
  },
  es: {
    nav:["Proyecto","Residencias","Inversión","Nuanu"],brochure:"Recibir el dossier",hero:"Donde el río|se encuentra con el océano.",intro:"15 residencias icónicas de YODEZEEN. Una colección excepcional entre selva tropical, cultura y horizonte.",access:"Acceso prioritario",discover:"Descubrir Luna",from:"Desde",collection:"Colección",delivery:"Entrega",vision:"La visión",visionTitle:"Más que una dirección.|Una nueva forma de|vivir Bali.",visionLead:"Luna Residences une arquitectura, hospitalidad y naturaleza en el ecosistema vivo de Nuanu.",visionBody:"Cada residencia se abre al océano, al río o a la selva. Las líneas fluidas de YODEZEEN prolongan el paisaje con gestión cinco estrellas 24/7.",essentials:"Lo esencial",roi:"ROI anual proyectado*",lease:"Leasehold de larga duración",down:"Pago inicial",beach:"De la playa de Nyanyi",disclaimer:"*Proyección indicativa, no garantizada. Depende de ocupación, costes, mercado y residencia.",coll:"La colección",collTitle:"Cinco formas de vivir|al ritmo de Luna.",collIntro:"Del estudio íntimo al penthouse, cada tipología privilegia vistas, terrazas y luz.",lifestyle:"El privilegio Luna",lifestyleTitle:"El beach club se convierte|en tu día a día.",lifestyleBody:"La hospitalidad y energía creativa de Luna Beach Club llegan hasta tu residencia.",nuanuTitle:"44 hectáreas.|Un mundo propio.",nuanuBody:"Arte, gastronomía, educación, bienestar y naturaleza en un destino costero activo todo el año.",invest:"Inversión",investTitle:"Un activo excepcional.|Gestión sin esfuerzo.",investBody:"Una colección limitada, un destino en crecimiento y gestión hotelera completa unen uso personal y potencial de alquiler.",payment:"Plan de pagos",paymentTitle:"Avanza|a tu ritmo.",faq:"Preguntas frecuentes",faqTitle:"Todo lo que necesitas|saber.",contact:"Acceso prioritario",contactTitle:"Las mejores vistas|se eligen primero.",contactBody:"Recibe el dossier, planos, precios y disponibilidad actualizada.",name:"Tu nombre",phone:"WhatsApp / Teléfono",budget:"Presupuesto",goal:"Tu proyecto",select:"Seleccionar",consent:"Acepto que me contacten sobre Luna Residences.",submit:"Recibir el dossier completo",response:"Respuesta personalizada en 24 horas",privacy:"Sin spam. Tus datos son confidenciales.",footer:"INFORMACIÓN INDICATIVA, SUJETA A DISPONIBILIDAD.",pageTitles:{residences:"Residencias y planos",investment:"Invertir en Luna Residences",nuanu:"Vivir en Nuanu Creative City","buying-guide":"Comprar una propiedad en Bali"},pageKickers:{residences:"LA COLECCIÓN",investment:"LA OPORTUNIDAD",nuanu:"EL DESTINO","buying-guide":"GUÍA DE COMPRA"}
  },
  pt: {
    nav:["Projeto","Residências","Investimento","Nuanu"],brochure:"Receber o dossiê",hero:"Onde o rio|encontra o oceano.",intro:"15 residências icônicas da YODEZEEN. Uma coleção rara entre floresta tropical, cultura e horizonte.",access:"Acesso prioritário",discover:"Descobrir Luna",from:"A partir de",collection:"Coleção",delivery:"Entrega",vision:"A visão",visionTitle:"Mais que um endereço.|Uma nova forma de|viver Bali.",visionLead:"Luna Residences reúne arquitetura, hospitalidade e natureza no ecossistema vivo de Nuanu.",visionBody:"Cada residência se abre para o oceano, rio ou floresta. As linhas fluidas da YODEZEEN prolongam a paisagem com gestão cinco estrelas 24/7.",essentials:"O essencial",roi:"ROI anual projetado*",lease:"Leasehold de longa duração",down:"Entrada inicial",beach:"Da praia de Nyanyi",disclaimer:"*Projeção indicativa, não garantida. Depende de ocupação, custos, mercado e residência.",coll:"A coleção",collTitle:"Cinco formas de viver|no ritmo de Luna.",collIntro:"Do estúdio intimista à cobertura exclusiva, cada tipologia valoriza vistas, terraços e luz.",lifestyle:"O privilégio Luna",lifestyleTitle:"O beach club torna-se|parte do seu dia.",lifestyleBody:"A hospitalidade e energia criativa do Luna Beach Club chegam até sua residência.",nuanuTitle:"44 hectares.|Um mundo próprio.",nuanuBody:"Arte, gastronomia, educação, bem-estar e natureza em um destino costeiro ativo o ano todo.",invest:"Investimento",investTitle:"Um ativo raro.|Gestão sem esforço.",investBody:"Uma coleção limitada, um destino em crescimento e gestão hoteleira completa unem uso pessoal e potencial de locação.",payment:"Plano de pagamento",paymentTitle:"Avance|no seu ritmo.",faq:"Perguntas frequentes",faqTitle:"Tudo o que você precisa|saber.",contact:"Acesso prioritário",contactTitle:"As melhores vistas|são escolhidas primeiro.",contactBody:"Receba o dossiê, plantas, preços e disponibilidade atualizada.",name:"Seu nome",phone:"WhatsApp / Telefone",budget:"Orçamento",goal:"Seu objetivo",select:"Selecionar",consent:"Aceito ser contatado sobre Luna Residences.",submit:"Receber o dossiê completo",response:"Resposta personalizada em 24 horas",privacy:"Sem spam. Seus dados permanecem confidenciais.",footer:"INFORMAÇÕES INDICATIVAS, SUJEITAS À DISPONIBILIDADE.",pageTitles:{residences:"Residências e plantas",investment:"Investir em Luna Residences",nuanu:"Viver em Nuanu Creative City","buying-guide":"Comprar um imóvel em Bali"},pageKickers:{residences:"A COLEÇÃO",investment:"A OPORTUNIDADE",nuanu:"O DESTINO","buying-guide":"GUIA DE COMPRA"}
  }
};

export const detailCopy: Record<Locale, Record<PageKey, {intro:string; sections:{title:string;body:string}[]}>> = {
  en:{residences:{intro:"Explore five residence typologies designed around panoramic views, generous private terraces and refined YODEZEEN interiors.",sections:[{title:"Studios · 35–39 m²",body:"A bright, highly efficient retreat with an 11–14 m² terrace, kitchenette, living space and ocean or river views."},{title:"One-bedroom suites · 55–61 m²",body:"A complete residence with a separate bedroom, living room, dining area, kitchen and terraces up to 50 m²."},{title:"Family & signature residences",body:"Two- and three-bedroom layouts and a rare penthouse offer expansive living for families and long stays."}]},investment:{intro:"A limited pre-sale collection in one of Bali’s fastest-growing lifestyle destinations, supported by five-star property management.",sections:[{title:"Projected return",body:"Marketing projections indicate 10–14% annual ROI. Returns are not guaranteed and depend on occupancy, rates, costs and market conditions."},{title:"60+ year leasehold",body:"A long-term ownership structure designed for international buyers, with legal terms confirmed for each unit."},{title:"Managed 24/7",body:"Hospitality-grade operations support rentals, guest experience and property care with minimal owner involvement."}]},nuanu:{intro:"Discover a 44-hectare creative city where art, wellness, education, dining and nature shape daily life.",sections:[{title:"A year-round destination",body:"Nuanu supports more than one million annual visitors through cultural programming, festivals and destination venues."},{title:"Nature first",body:"Seventy percent of the masterplan is dedicated to natural landscape, including parks, river corridors and coastal ecosystems."},{title:"Everything within reach",body:"International education, restaurants, Lumeira Spa, art venues and Luna Beach Club form a walkable lifestyle ecosystem."}]},"buying-guide":{intro:"A clear overview of the purchase path for international buyers considering a residence in Bali.",sections:[{title:"1. Choose your residence",body:"Request current availability, compare views and layouts, and select the typology aligned with your use and investment goals."},{title:"2. Review the legal pack",body:"Independent legal advice is recommended before signing. Confirm lease term, extension rights, taxes, operating costs and payment milestones."},{title:"3. Reserve and complete",body:"Reservation options begin at USD 5,000. The standard payment schedule is 25% at signing, 25% in Q1 2027, 25% in Q1 2028 and 25% at handover."}]}},
  fr:{} as any,es:{} as any,pt:{} as any
};

detailCopy.fr = {
  residences:{intro:"Découvrez cinq typologies pensées autour des vues panoramiques, de grandes terrasses privées et des intérieurs YODEZEEN.",sections:[{title:"Studios · 35–39 m²",body:"Une retraite lumineuse avec terrasse de 11–14 m², kitchenette, salon et vue océan ou rivière."},{title:"Suites 1 chambre · 55–61 m²",body:"Une vraie résidence avec chambre séparée, séjour, salle à manger, cuisine et terrasse jusqu’à 50 m²."},{title:"Résidences familiales & signature",body:"Des plans de deux et trois chambres ainsi qu’un penthouse rare pour les familles et les longs séjours."}]},
  investment:{intro:"Une collection en prévente très limitée au cœur d’une des destinations lifestyle les plus dynamiques de Bali.",sections:[{title:"Rendement projeté",body:"Les projections marketing indiquent 10–14 % par an. Le rendement n’est pas garanti et dépend de l’occupation, des tarifs, des charges et du marché."},{title:"Leasehold 60+ ans",body:"Une structure longue durée pensée pour les acheteurs internationaux, avec conditions juridiques confirmées pour chaque unité."},{title:"Gestion 24/7",body:"Une exploitation hôtelière complète accompagne la location, l’expérience client et l’entretien du bien."}]},
  nuanu:{intro:"Découvrez une ville créative de 44 hectares où art, bien-être, éducation, gastronomie et nature façonnent le quotidien.",sections:[{title:"Une destination toute l’année",body:"Nuanu accueille plus d’un million de visiteurs annuels grâce aux festivals, à la culture et à ses lieux de destination."},{title:"La nature d’abord",body:"70 % du masterplan est réservé aux paysages naturels, aux parcs, à la rivière et aux écosystèmes côtiers."},{title:"Tout à proximité",body:"École internationale, restaurants, Lumeira Spa, art et Luna Beach Club composent un écosystème accessible."}]},
  "buying-guide":{intro:"Un parcours clair pour les acheteurs internationaux qui envisagent une résidence à Bali.",sections:[{title:"1. Choisir la résidence",body:"Consultez les disponibilités, comparez les vues et les plans, puis choisissez selon votre usage et vos objectifs."},{title:"2. Étudier le dossier juridique",body:"Un conseil juridique indépendant est recommandé. Vérifiez durée du bail, extensions, taxes, charges et échéancier."},{title:"3. Réserver et finaliser",body:"La réservation commence à 5 000 USD. Échéancier standard : 25 % à la signature, 25 % au T1 2027, 25 % au T1 2028 et 25 % à la livraison."}]}
};

detailCopy.es={
 residences:{intro:"Descubre cinco tipologías diseñadas alrededor de vistas panorámicas, terrazas privadas e interiores YODEZEEN.",sections:[{title:"Estudios · 35–39 m²",body:"Un refugio luminoso con terraza de 11–14 m², kitchenette, salón y vistas al océano o al río."},{title:"Suites de 1 dormitorio · 55–61 m²",body:"Una residencia completa con dormitorio independiente, salón, comedor, cocina y terrazas de hasta 50 m²."},{title:"Residencias familiares y exclusivas",body:"Distribuciones de dos y tres dormitorios y un penthouse excepcional para familias y largas estancias."}]},
 investment:{intro:"Una colección de preventa limitada en uno de los destinos lifestyle de mayor crecimiento de Bali.",sections:[{title:"Rentabilidad proyectada",body:"Las proyecciones comerciales indican un 10–14 % anual. No está garantizado y depende de ocupación, tarifas, costes y mercado."},{title:"Leasehold de más de 60 años",body:"Una estructura de larga duración para compradores internacionales, con condiciones legales confirmadas por unidad."},{title:"Gestión 24/7",body:"La operación hotelera se ocupa del alquiler, la experiencia del huésped y el mantenimiento de la propiedad."}]},
 nuanu:{intro:"Descubre una ciudad creativa de 44 hectáreas donde arte, bienestar, educación, gastronomía y naturaleza forman la vida diaria.",sections:[{title:"Un destino todo el año",body:"Nuanu recibe más de un millón de visitantes anuales gracias a su programación cultural, festivales y espacios únicos."},{title:"La naturaleza primero",body:"El 70 % del plan maestro está dedicado al paisaje natural, parques, río y ecosistemas costeros."},{title:"Todo a tu alcance",body:"Educación internacional, restaurantes, Lumeira Spa, arte y Luna Beach Club forman un ecosistema accesible."}]},
 "buying-guide":{intro:"Una guía clara del proceso de compra para compradores internacionales en Bali.",sections:[{title:"1. Elige tu residencia",body:"Consulta la disponibilidad, compara vistas y planos y selecciona la tipología que se adapte a tus objetivos."},{title:"2. Revisa la documentación legal",body:"Se recomienda asesoría jurídica independiente. Confirma plazo, extensiones, impuestos, costes y calendario de pagos."},{title:"3. Reserva y completa",body:"Las reservas comienzan en 5.000 USD. El plan estándar es 25 % a la firma, 25 % en T1 2027, 25 % en T1 2028 y 25 % a la entrega."}]}
};
detailCopy.pt={
 residences:{intro:"Conheça cinco tipologias criadas em torno de vistas panorâmicas, terraços privativos e interiores YODEZEEN.",sections:[{title:"Estúdios · 35–39 m²",body:"Um refúgio luminoso com terraço de 11–14 m², kitchenette, sala e vista para o oceano ou rio."},{title:"Suítes de 1 quarto · 55–61 m²",body:"Uma residência completa com quarto separado, sala, jantar, cozinha e terraços de até 50 m²."},{title:"Residências familiares e exclusivas",body:"Plantas de dois e três quartos e uma cobertura rara para famílias e estadias prolongadas."}]},
 investment:{intro:"Uma coleção limitada de pré-venda em um dos destinos lifestyle que mais crescem em Bali.",sections:[{title:"Retorno projetado",body:"As projeções comerciais indicam 10–14 % ao ano. Não é garantido e depende de ocupação, tarifas, custos e mercado."},{title:"Leasehold de mais de 60 anos",body:"Uma estrutura de longo prazo para compradores internacionais, com condições jurídicas confirmadas por unidade."},{title:"Gestão 24/7",body:"A operação hoteleira cuida da locação, experiência dos hóspedes e manutenção da propriedade."}]},
 nuanu:{intro:"Conheça uma cidade criativa de 44 hectares onde arte, bem-estar, educação, gastronomia e natureza definem o cotidiano.",sections:[{title:"Um destino o ano todo",body:"Nuanu recebe mais de um milhão de visitantes anuais graças à programação cultural, festivais e destinos únicos."},{title:"Natureza em primeiro lugar",body:"70 % do plano diretor é dedicado à paisagem natural, parques, rio e ecossistemas costeiros."},{title:"Tudo ao seu alcance",body:"Educação internacional, restaurantes, Lumeira Spa, arte e Luna Beach Club formam um ecossistema acessível."}]},
 "buying-guide":{intro:"Um guia claro do processo de compra para investidores internacionais em Bali.",sections:[{title:"1. Escolha sua residência",body:"Consulte a disponibilidade, compare vistas e plantas e escolha a tipologia alinhada aos seus objetivos."},{title:"2. Revise a documentação legal",body:"Recomenda-se assessoria jurídica independente. Confirme prazo, extensões, impostos, custos e calendário de pagamentos."},{title:"3. Reserve e conclua",body:"As reservas começam em USD 5.000. Plano padrão: 25 % na assinatura, 25 % no T1 2027, 25 % no T1 2028 e 25 % na entrega."}]}
};

export const residenceData: Record<Locale, {title:string;area:string;terrace:string;desc:string}[]> = {
  en:[{title:"Studio",area:"35–39 m²",terrace:"11–14 m² terrace",desc:"Kitchenette · living area · ocean or river view"},{title:"1BR Suite",area:"55–61 m²",terrace:"15–50 m² terrace",desc:"Full bedroom · living room · dining · kitchen"},{title:"2BR Family Suite",area:"≈ 94 m²",terrace:"≈ 25 m² terrace",desc:"Master suite · second bedroom · generous living"}],
  fr:[{title:"Studio",area:"35–39 m²",terrace:"Terrasse 11–14 m²",desc:"Kitchenette · salon · vue océan ou rivière"},{title:"Suite 1 chambre",area:"55–61 m²",terrace:"Terrasse 15–50 m²",desc:"Chambre · séjour · salle à manger · cuisine"},{title:"Suite familiale 2 chambres",area:"≈ 94 m²",terrace:"Terrasse ≈ 25 m²",desc:"Suite master · seconde chambre · grand séjour"}],
  es:[{title:"Estudio",area:"35–39 m²",terrace:"Terraza 11–14 m²",desc:"Kitchenette · salón · vista al océano o río"},{title:"Suite 1 dormitorio",area:"55–61 m²",terrace:"Terraza 15–50 m²",desc:"Dormitorio · salón · comedor · cocina"},{title:"Suite familiar 2 dormitorios",area:"≈ 94 m²",terrace:"Terraza ≈ 25 m²",desc:"Suite principal · segundo dormitorio · gran salón"}],
  pt:[{title:"Estúdio",area:"35–39 m²",terrace:"Terraço 11–14 m²",desc:"Kitchenette · sala · vista oceano ou rio"},{title:"Suíte 1 quarto",area:"55–61 m²",terrace:"Terraço 15–50 m²",desc:"Quarto · sala · jantar · cozinha"},{title:"Suíte familiar 2 quartos",area:"≈ 94 m²",terrace:"Terraço ≈ 25 m²",desc:"Suíte master · segundo quarto · sala ampla"}]
};

export function routeFor(locale:Locale, page?:string){ return locale === "en" ? (page ? `/${page}` : "/") : (page ? `/${locale}/${page}` : `/${locale}`); }
export function alternates(page?:string){ return Object.fromEntries(locales.map(l=>[l,`${baseUrl}${routeFor(l,page)}`]).concat([["x-default",`${baseUrl}${routeFor("en",page)}`]])); }
